CREATE TABLE `sys_attachment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件记录主键，数据库自增生成',
  `file_id` BIGINT UNSIGNED NOT NULL COMMENT '底层文件记录 ID，对应 sys_file.id',
  `display_name` VARCHAR(255) NOT NULL COMMENT '附件展示名，默认使用原始文件名',
  `category` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '附件分类，例如 invoice、contract、avatar',
  `biz_type` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务类型，用于区分模块接入来源',
  `uploader_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '上传用户 ID，对应 sys_user.id',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '附件状态：1 启用，2 停用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_attachment_file_id` (`file_id`),
  KEY `idx_sys_attachment_category` (`category`),
  KEY `idx_sys_attachment_biz_type` (`biz_type`),
  KEY `idx_sys_attachment_uploader_id` (`uploader_id`),
  KEY `idx_sys_attachment_status` (`status`),
  KEY `idx_sys_attachment_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='附件中心表';
