-- Stable full initialization SQL for mysql.
-- Generated by scripts/build-full-migrations.sh.
--
-- Covers final schema + built-in seed data.
-- Does NOT create the first admin user.
-- Create the first admin with POST /api/v1/setup/init after import.

-- ============================================================================
-- Final schema
-- ============================================================================

-- 系统用户表
CREATE TABLE `sys_user` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '用户记录主键，数据库自增生成',
  `username` VARCHAR(64) NOT NULL COMMENT '登录用户名',
  `password_hash` VARCHAR(255) NOT NULL COMMENT '密码哈希',
  `nickname` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '管理台展示名称',
  `department_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '部门 ID，对应 sys_department.id',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '用户状态：1 启用，2 禁用',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_username` (`username`),
  KEY `idx_sys_user_department_id` (`department_id`),
  KEY `idx_sys_user_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='后台用户表';

-- 系统角色表
CREATE TABLE `sys_role` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '角色记录主键，数据库自增生成',
  `code` VARCHAR(64) NOT NULL COMMENT '角色编码',
  `name` VARCHAR(64) NOT NULL COMMENT '角色名称',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，数字越小越靠前',
  `data_scope` VARCHAR(32) NOT NULL DEFAULT 'self' COMMENT '数据权限范围：all/dept/dept_and_children/self/custom_dept',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '角色状态：1 启用，2 禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_role_code` (`code`),
  KEY `idx_sys_role_status` (`status`),
  KEY `idx_sys_role_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='后台角色表';

-- 用户角色关系表
CREATE TABLE `sys_user_role` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关系记录主键，数据库自增生成',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户 ID，对应 sys_user.id',
  `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色 ID，对应 sys_role.id',
  `created_at` DATETIME(3) NOT NULL COMMENT '绑定时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_role_user_role` (`user_id`, `role_id`),
  KEY `idx_sys_user_role_user_id` (`user_id`),
  KEY `idx_sys_user_role_role_id` (`role_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户角色关系表';

-- 系统菜单和按钮表
CREATE TABLE `sys_menu` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '菜单记录主键，数据库自增生成',
  `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父级菜单 ID，根节点为 0',
  `type` SMALLINT NOT NULL COMMENT '节点类型：1 目录，2 菜单，3 按钮',
  `code` VARCHAR(128) NOT NULL COMMENT '菜单或按钮编码，系统内唯一',
  `title` VARCHAR(64) NOT NULL COMMENT '展示名称',
  `path` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '前端路由路径',
  `component` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '前端组件路径',
  `icon` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '图标标识',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，数字越小越靠前',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '菜单状态：1 启用，2 禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_menu_code` (`code`),
  KEY `idx_sys_menu_parent_id` (`parent_id`),
  KEY `idx_sys_menu_type` (`type`),
  KEY `idx_sys_menu_status` (`status`),
  KEY `idx_sys_menu_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='后台菜单和按钮表';

-- 角色菜单关系表
CREATE TABLE `sys_role_menu` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关系记录主键，数据库自增生成',
  `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色 ID，对应 sys_role.id',
  `menu_id` BIGINT UNSIGNED NOT NULL COMMENT '菜单 ID，对应 sys_menu.id',
  `created_at` DATETIME(3) NOT NULL COMMENT '绑定时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_role_menu_role_menu` (`role_id`, `menu_id`),
  KEY `idx_sys_role_menu_role_id` (`role_id`),
  KEY `idx_sys_role_menu_menu_id` (`menu_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色菜单关系表';

-- 接口权限元数据表
CREATE TABLE `sys_api` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '接口权限记录主键，数据库自增生成',
  `code` VARCHAR(128) NOT NULL COMMENT '接口权限编码，系统内唯一',
  `name` VARCHAR(64) NOT NULL COMMENT '接口权限名称',
  `module` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '所属模块，例如 iam、system、audit',
  `method` VARCHAR(16) NOT NULL COMMENT 'HTTP 方法',
  `path` VARCHAR(255) NOT NULL COMMENT '接口路径模式',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，数字越小越靠前',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '接口权限状态：1 启用，2 禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_api_code` (`code`),
  UNIQUE KEY `uk_sys_api_method_path` (`method`, `path`),
  KEY `idx_sys_api_module` (`module`),
  KEY `idx_sys_api_status` (`status`),
  KEY `idx_sys_api_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='接口权限元数据表';

-- 角色接口权限关系表
CREATE TABLE `sys_role_api` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关系记录主键，数据库自增生成',
  `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色 ID，对应 sys_role.id',
  `api_id` BIGINT UNSIGNED NOT NULL COMMENT '接口权限 ID，对应 sys_api.id',
  `created_at` DATETIME(3) NOT NULL COMMENT '绑定时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_role_api_role_api` (`role_id`, `api_id`),
  KEY `idx_sys_role_api_role_id` (`role_id`),
  KEY `idx_sys_role_api_api_id` (`api_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='角色接口权限关系表';

-- 系统配置表
CREATE TABLE `sys_config` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '配置记录主键，数据库自增生成',
  `group_code` VARCHAR(64) NOT NULL COMMENT '配置分组，例如 site、upload',
  `config_key` VARCHAR(128) NOT NULL COMMENT '配置键，系统内唯一，例如 site:title',
  `name` VARCHAR(64) NOT NULL COMMENT '配置名称',
  `value` TEXT NOT NULL COMMENT '配置值，统一按字符串存储',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，数字越小越靠前',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '配置状态：1 启用，2 禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_config_key` (`config_key`),
  KEY `idx_sys_config_group_code` (`group_code`),
  KEY `idx_sys_config_status` (`status`),
  KEY `idx_sys_config_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统配置表';

-- 文件上传记录表
CREATE TABLE `sys_file` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '文件记录主键，数据库自增生成',
  `storage` VARCHAR(32) NOT NULL DEFAULT 'local' COMMENT '存储类型，本节使用 local',
  `original_name` VARCHAR(255) NOT NULL COMMENT '用户上传时的原始文件名',
  `file_name` VARCHAR(255) NOT NULL COMMENT '后端生成的保存文件名',
  `ext` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '文件后缀，例如 .png、.pdf',
  `mime_type` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '上传请求中的文件 MIME 类型',
  `size` BIGINT NOT NULL DEFAULT 0 COMMENT '文件大小，单位字节',
  `sha256` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '文件内容 SHA-256 哈希',
  `path` VARCHAR(500) NOT NULL COMMENT '服务端保存路径',
  `url` VARCHAR(500) NOT NULL COMMENT '前端可访问地址',
  `uploader_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '上传用户 ID，对应 sys_user.id',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '文件状态：1 启用，2 停用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  KEY `idx_sys_file_ext` (`ext`),
  KEY `idx_sys_file_sha256` (`sha256`),
  KEY `idx_sys_file_uploader_id` (`uploader_id`),
  KEY `idx_sys_file_status` (`status`),
  KEY `idx_sys_file_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='文件上传记录表';

-- 操作日志表
CREATE TABLE `sys_operation_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '操作日志主键，数据库自增生成',
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '操作人 ID，对应 sys_user.id',
  `username` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '操作人用户名',
  `method` VARCHAR(10) NOT NULL COMMENT 'HTTP 请求方法',
  `path` VARCHAR(255) NOT NULL COMMENT '实际请求路径',
  `route_path` VARCHAR(255) NOT NULL DEFAULT '' COMMENT 'Gin 路由模板',
  `query` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '查询参数',
  `ip` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户端 IP',
  `user_agent` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '浏览器或客户端标识',
  `status_code` INT NOT NULL DEFAULT 0 COMMENT 'HTTP 状态码',
  `latency_ms` BIGINT NOT NULL DEFAULT 0 COMMENT '请求耗时，单位毫秒',
  `success` BOOLEAN NOT NULL DEFAULT TRUE COMMENT '是否成功',
  `error_message` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '错误摘要',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_sys_operation_log_user_id` (`user_id`),
  KEY `idx_sys_operation_log_username` (`username`),
  KEY `idx_sys_operation_log_method` (`method`),
  KEY `idx_sys_operation_log_path` (`path`),
  KEY `idx_sys_operation_log_route_path` (`route_path`),
  KEY `idx_sys_operation_log_status_code` (`status_code`),
  KEY `idx_sys_operation_log_success` (`success`),
  KEY `idx_sys_operation_log_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='操作日志表';

-- 登录日志表
CREATE TABLE `sys_login_log` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '登录日志主键，数据库自增生成',
  `user_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '用户 ID，对应 sys_user.id；用户名不存在时为 0',
  `username` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '登录用户名',
  `status` SMALLINT NOT NULL COMMENT '登录状态：1 成功，2 失败',
  `message` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '登录结果说明',
  `ip` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '客户端 IP',
  `user_agent` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '浏览器或客户端标识',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_sys_login_log_user_id` (`user_id`),
  KEY `idx_sys_login_log_username` (`username`),
  KEY `idx_sys_login_log_status` (`status`),
  KEY `idx_sys_login_log_ip` (`ip`),
  KEY `idx_sys_login_log_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='登录日志表';

-- 公告表
CREATE TABLE `sys_notice` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '公告记录主键，数据库自增生成',
  `title` VARCHAR(128) NOT NULL COMMENT '公告标题',
  `content` TEXT NOT NULL COMMENT '公告内容',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，数字越小越靠前',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '公告状态：1 启用，2 禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  KEY `idx_sys_notice_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='公告表';

-- Casbin 权限策略表
CREATE TABLE `casbin_rule` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '策略记录主键，数据库自增生成',
  `ptype` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '策略类型，例如 p',
  `v0` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '策略主体，本项目存角色编码',
  `v1` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '资源路径',
  `v2` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '请求方法',
  `v3` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '预留字段',
  `v4` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '预留字段',
  `v5` VARCHAR(100) NOT NULL DEFAULT '' COMMENT '预留字段',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_casbin_rule_policy` (`ptype`, `v0`, `v1`, `v2`, `v3`, `v4`, `v5`),
  KEY `idx_casbin_rule_ptype` (`ptype`),
  KEY `idx_casbin_rule_subject` (`v0`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Casbin 权限策略表';

CREATE TABLE `sys_department` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '部门记录主键，数据库自增生成',
  `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '父部门 ID，根节点为 0',
  `ancestors` VARCHAR(500) NOT NULL DEFAULT '' COMMENT '祖先路径，例如 0,1,3',
  `name` VARCHAR(64) NOT NULL COMMENT '部门名称',
  `code` VARCHAR(64) NOT NULL COMMENT '部门编码',
  `leader_user_id` BIGINT UNSIGNED NULL DEFAULT NULL COMMENT '负责人用户 ID，未设置时为 NULL',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，数字越小越靠前',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '部门状态：1 启用，2 禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_department_code` (`code`),
  KEY `idx_sys_department_parent_id` (`parent_id`),
  KEY `idx_sys_department_leader_user_id` (`leader_user_id`),
  KEY `idx_sys_department_status` (`status`),
  KEY `idx_sys_department_deleted_at` (`deleted_at`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='组织部门表';

CREATE TABLE `sys_post` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '岗位记录主键，数据库自增生成',
  `code` VARCHAR(64) NOT NULL COMMENT '岗位编码',
  `name` VARCHAR(64) NOT NULL COMMENT '岗位名称',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，数字越小越靠前',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '岗位状态：1 启用，2 禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_post_code` (`code`),
  KEY `idx_sys_post_status` (`status`),
  KEY `idx_sys_post_deleted_at` (`deleted_at`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='岗位表';

CREATE TABLE `sys_user_post` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关系记录主键，数据库自增生成',
  `user_id` BIGINT UNSIGNED NOT NULL COMMENT '用户 ID，对应 sys_user.id',
  `post_id` BIGINT UNSIGNED NOT NULL COMMENT '岗位 ID，对应 sys_post.id',
  `created_at` DATETIME(3) NOT NULL COMMENT '绑定时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_user_post_user_post` (`user_id`, `post_id`),
  KEY `idx_sys_user_post_user_id` (`user_id`),
  KEY `idx_sys_user_post_post_id` (`post_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='用户岗位关系表';

CREATE TABLE `sys_role_data_scope` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '关系记录主键，数据库自增生成',
  `role_id` BIGINT UNSIGNED NOT NULL COMMENT '角色 ID，对应 sys_role.id',
  `department_id` BIGINT UNSIGNED NOT NULL COMMENT '部门 ID，对应 sys_department.id',
  `created_at` DATETIME(3) NOT NULL COMMENT '绑定时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_role_data_scope_role_department` (`role_id`, `department_id`),
  KEY `idx_sys_role_data_scope_role_id` (`role_id`),
  KEY `idx_sys_role_data_scope_department_id` (`department_id`)
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci
  COMMENT='角色自定义部门数据范围关系表';

CREATE TABLE `sys_dict_type` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '字典类型主键，数据库自增生成',
  `code` VARCHAR(64) NOT NULL COMMENT '字典编码，系统内唯一',
  `name` VARCHAR(64) NOT NULL COMMENT '字典名称',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，数字越小越靠前',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '字典状态：1 启用，2 禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_dict_type_code` (`code`),
  KEY `idx_sys_dict_type_status` (`status`),
  KEY `idx_sys_dict_type_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统字典类型表';

CREATE TABLE `sys_dict_item` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '字典项主键，数据库自增生成',
  `type_id` BIGINT UNSIGNED NOT NULL COMMENT '字典类型 ID，对应 sys_dict_type.id',
  `item_key` VARCHAR(64) NOT NULL COMMENT '字典项编码，同一类型内唯一',
  `label` VARCHAR(64) NOT NULL COMMENT '字典项名称',
  `value` VARCHAR(255) NOT NULL COMMENT '字典项值',
  `tag_type` VARCHAR(32) NOT NULL DEFAULT '' COMMENT '前端标签样式提示',
  `sort` INT NOT NULL DEFAULT 0 COMMENT '排序值，数字越小越靠前',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '字典项状态：1 启用，2 禁用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_dict_item_type_key` (`type_id`, `item_key`),
  KEY `idx_sys_dict_item_type_id` (`type_id`),
  KEY `idx_sys_dict_item_status` (`status`),
  KEY `idx_sys_dict_item_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='系统字典项表';

CREATE TABLE `sys_attachment` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '附件记录主键，数据库自增生成',
  `file_id` BIGINT UNSIGNED NOT NULL COMMENT '底层文件记录 ID，对应 sys_file.id',
  `display_name` VARCHAR(255) NOT NULL COMMENT '附件展示名，默认使用原始文件名',
  `category` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '附件分类，例如 invoice、contract、avatar',
  `biz_type` VARCHAR(64) NOT NULL DEFAULT '' COMMENT '业务类型，用于区分模块接入来源',
  `uploader_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '上传用户 ID，对应 sys_user.id',
  `status` SMALLINT NOT NULL DEFAULT 1 COMMENT '附件状态：1 启用，2 停用',
  `remark` VARCHAR(255) NOT NULL DEFAULT '' COMMENT '备注',
  `created_at` DATETIME(3) NOT NULL COMMENT '创建时间',
  `updated_at` DATETIME(3) NOT NULL COMMENT '更新时间',
  `deleted_at` DATETIME(3) NULL DEFAULT NULL COMMENT '逻辑删除时间，NULL 表示未删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_sys_attachment_file_id` (`file_id`),
  KEY `idx_sys_attachment_category` (`category`),
  KEY `idx_sys_attachment_biz_type` (`biz_type`),
  KEY `idx_sys_attachment_uploader_id` (`uploader_id`),
  KEY `idx_sys_attachment_status` (`status`),
  KEY `idx_sys_attachment_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='附件中心表';

CREATE TABLE sys_notification (
    id         BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    user_id    BIGINT UNSIGNED NOT NULL,
    type       SMALLINT NOT NULL DEFAULT 1,
    title      VARCHAR(128) NOT NULL DEFAULT '',
    content    TEXT NOT NULL DEFAULT '',
    extra      JSON,
    is_read    TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    read_at    DATETIME NULL,
    INDEX idx_notification_user_unread (user_id, is_read, created_at DESC)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- ============================================================================
-- Built-in seed data
-- ============================================================================

INSERT INTO `sys_role` (`id`, `code`, `name`, `sort`, `data_scope`, `status`, `remark`, `created_at`, `updated_at`)
VALUES
  (1, 'super_admin', '超级管理员', 0, 'all', 1, '系统内置角色', NOW(3), NOW(3));

INSERT INTO `sys_menu` (`id`, `parent_id`, `type`, `code`, `title`, `path`, `component`, `icon`, `sort`, `status`, `remark`, `created_at`, `updated_at`)
VALUES
  (100, 0, 1, 'iam', '权限管理', '/iam', '', 'shield', 20, 1, '系统内置目录', NOW(3), NOW(3)),
  (101, 0, 1, 'system', '系统设置', '/system', '', 'setting', 30, 1, '系统内置目录', NOW(3), NOW(3)),
  (102, 0, 1, 'audit', '审计监控', '/audit', '', 'analytics', 40, 1, '系统内置目录', NOW(3), NOW(3)),
  (211, 100, 2, 'system:department', '部门管理', '/iam/departments', 'iam/DepartmentView', 'git-branch', 10, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1110, 211, 3, 'system:department:list', '查看部门', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1111, 211, 3, 'system:department:create', '创建部门', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1112, 211, 3, 'system:department:update', '编辑部门', '', '', '', 30, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1113, 211, 3, 'system:department:status', '修改部门状态', '', '', '', 40, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1114, 211, 3, 'system:department:delete', '删除部门', '', '', '', 50, 1, '系统内置按钮', NOW(3), NOW(3)),
  (212, 100, 2, 'system:post', '岗位管理', '/iam/posts', 'iam/PostView', 'briefcase', 20, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1120, 212, 3, 'system:post:list', '查看岗位', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1121, 212, 3, 'system:post:create', '创建岗位', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1122, 212, 3, 'system:post:update', '编辑岗位', '', '', '', 30, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1123, 212, 3, 'system:post:status', '修改岗位状态', '', '', '', 40, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1124, 212, 3, 'system:post:delete', '删除岗位', '', '', '', 50, 1, '系统内置按钮', NOW(3), NOW(3)),
  (201, 100, 2, 'system:user', '用户管理', '/iam/users', 'iam/UserView', 'people', 30, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1010, 201, 3, 'system:user:list', '查看用户', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1011, 201, 3, 'system:user:create', '创建用户', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1012, 201, 3, 'system:user:update', '编辑用户', '', '', '', 30, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1013, 201, 3, 'system:user:status', '修改用户状态', '', '', '', 40, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1014, 201, 3, 'system:user:assign-role', '分配用户角色', '', '', '', 50, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1015, 201, 3, 'system:user:delete', '删除用户', '', '', '', 60, 1, '系统内置按钮', NOW(3), NOW(3)),
  (202, 100, 2, 'system:role', '角色管理', '/iam/roles', 'iam/RoleView', 'shield', 40, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1020, 202, 3, 'system:role:list', '查看角色', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1021, 202, 3, 'system:role:create', '创建角色', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1022, 202, 3, 'system:role:update', '编辑角色', '', '', '', 30, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1023, 202, 3, 'system:role:status', '修改角色状态', '', '', '', 40, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1024, 202, 3, 'system:role:permission', '分配接口权限', '', '', '', 50, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1025, 202, 3, 'system:role:menu', '分配菜单权限', '', '', '', 60, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1026, 202, 3, 'system:role:delete', '删除角色', '', '', '', 70, 1, '系统内置按钮', NOW(3), NOW(3)),
  (203, 100, 2, 'system:menu', '菜单管理', '/iam/menus', 'iam/MenuView', 'layers', 50, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1030, 203, 3, 'system:menu:list', '查看菜单', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1031, 203, 3, 'system:menu:create', '创建菜单', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1032, 203, 3, 'system:menu:update', '编辑菜单', '', '', '', 30, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1033, 203, 3, 'system:menu:status', '修改菜单状态', '', '', '', 40, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1034, 203, 3, 'system:menu:delete', '删除菜单', '', '', '', 50, 1, '系统内置按钮', NOW(3), NOW(3)),
  (204, 101, 2, 'system:config', '系统配置', '/system/configs', 'system/ConfigView', 'cog', 10, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1040, 204, 3, 'system:config:list', '查看配置', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1041, 204, 3, 'system:config:create', '创建配置', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1042, 204, 3, 'system:config:update', '编辑配置', '', '', '', 30, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1043, 204, 3, 'system:config:status', '修改配置状态', '', '', '', 40, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1044, 204, 3, 'system:config:value', '读取配置值', '', '', '', 50, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1045, 204, 3, 'system:config:delete', '删除配置', '', '', '', 60, 1, '系统内置按钮', NOW(3), NOW(3)),
  (209, 101, 2, 'system:dict', '数据字典', '/system/dicts', 'system/DictView', 'albums', 20, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1090, 209, 3, 'system:dict:type:list', '查看字典类型', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1091, 209, 3, 'system:dict:type:create', '创建字典类型', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1092, 209, 3, 'system:dict:type:update', '编辑字典类型', '', '', '', 30, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1093, 209, 3, 'system:dict:type:status', '修改字典类型状态', '', '', '', 40, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1098, 209, 3, 'system:dict:type:delete', '删除字典类型', '', '', '', 45, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1094, 209, 3, 'system:dict:item:list', '查看字典项', '', '', '', 50, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1095, 209, 3, 'system:dict:item:create', '创建字典项', '', '', '', 60, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1096, 209, 3, 'system:dict:item:update', '编辑字典项', '', '', '', 70, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1097, 209, 3, 'system:dict:item:status', '修改字典项状态', '', '', '', 80, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1099, 209, 3, 'system:dict:item:delete', '删除字典项', '', '', '', 90, 1, '系统内置按钮', NOW(3), NOW(3)),
  (205, 101, 2, 'system:file', '文件管理', '/system/files', 'system/FileView', 'folder', 30, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1050, 205, 3, 'system:file:list', '查看文件', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1051, 205, 3, 'system:file:upload', '上传文件', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (210, 101, 2, 'system:attachment', '附件中心', '/system/attachments', 'system/AttachmentView', 'files', 40, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1100, 210, 3, 'system:attachment:list', '查看附件', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1101, 210, 3, 'system:attachment:upload', '上传附件', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1102, 210, 3, 'system:attachment:update', '编辑附件', '', '', '', 30, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1103, 210, 3, 'system:attachment:status', '修改附件状态', '', '', '', 40, 1, '系统内置按钮', NOW(3), NOW(3)),
  (208, 101, 2, 'system:notice', '公告管理', '/system/notices', 'system/NoticeView', 'notifications', 50, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1080, 208, 3, 'system:notice:list', '查看公告', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1081, 208, 3, 'system:notice:create', '创建公告', '', '', '', 20, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1082, 208, 3, 'system:notice:update', '编辑公告', '', '', '', 30, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1083, 208, 3, 'system:notice:status', '修改公告状态', '', '', '', 40, 1, '系统内置按钮', NOW(3), NOW(3)),
  (1084, 208, 3, 'system:notice:delete', '删除公告', '', '', '', 50, 1, '系统内置按钮', NOW(3), NOW(3)),
  (200, 102, 2, 'system:health', '系统状态', '/audit/health', 'system/HealthView', 'pulse', 10, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1001, 200, 3, 'system:health:view', '查看系统状态', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (206, 102, 2, 'system:operation-log', '操作日志', '/audit/operation-logs', 'system/OperationLogView', 'list', 20, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1060, 206, 3, 'system:operation-log:list', '查看操作日志', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3)),
  (207, 102, 2, 'system:login-log', '登录日志', '/audit/login-logs', 'system/LoginLogView', 'time', 30, 1, '系统内置菜单', NOW(3), NOW(3)),
  (1070, 207, 3, 'system:login-log:list', '查看登录日志', '', '', '', 10, 1, '系统内置按钮', NOW(3), NOW(3));

INSERT INTO `sys_dict_type` (`id`, `code`, `name`, `sort`, `status`, `remark`, `created_at`, `updated_at`)
VALUES
  (1, 'common:yes-no', '是否字典', 10, 1, '系统内置基础字典', NOW(3), NOW(3)),
  (2, 'notice:level', '公告级别', 20, 1, '系统内置公告字典', NOW(3), NOW(3));

INSERT INTO `sys_dict_item` (`id`, `type_id`, `item_key`, `label`, `value`, `tag_type`, `sort`, `status`, `remark`, `created_at`, `updated_at`)
VALUES
  (1, 1, 'yes', '是', '1', 'success', 10, 1, '系统内置基础字典项', NOW(3), NOW(3)),
  (2, 1, 'no', '否', '0', 'default', 20, 1, '系统内置基础字典项', NOW(3), NOW(3)),
  (3, 2, 'info', '普通公告', 'info', 'info', 10, 1, '系统内置公告字典项', NOW(3), NOW(3)),
  (4, 2, 'warning', '重要公告', 'warning', 'warning', 20, 1, '系统内置公告字典项', NOW(3), NOW(3));

INSERT INTO `sys_api` (`id`, `code`, `name`, `module`, `method`, `path`, `sort`, `status`, `remark`, `created_at`, `updated_at`)
VALUES
  (1, 'system:api:list', '查看接口权限元数据', 'iam', 'GET', '/api/v1/system/apis', 10, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (2, 'system:health:view', '查看系统状态', 'audit', 'GET', '/api/v1/system/health', 10, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (3, 'system:user:list', '查看用户', 'iam', 'GET', '/api/v1/system/users', 30, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (4, 'system:user:create', '创建用户', 'iam', 'POST', '/api/v1/system/users', 31, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (5, 'system:user:update', '编辑用户', 'iam', 'POST', '/api/v1/system/users/:id/update', 32, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (6, 'system:user:status', '修改用户状态', 'iam', 'POST', '/api/v1/system/users/:id/status', 33, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (7, 'system:user:assign-role', '分配用户角色', 'iam', 'POST', '/api/v1/system/users/:id/roles', 34, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (8, 'system:user:delete', '删除用户', 'iam', 'POST', '/api/v1/system/users/:id/delete', 35, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (9, 'system:role:list', '查看角色', 'iam', 'GET', '/api/v1/system/roles', 40, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (10, 'system:role:create', '创建角色', 'iam', 'POST', '/api/v1/system/roles', 41, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (11, 'system:role:update', '编辑角色', 'iam', 'POST', '/api/v1/system/roles/:id/update', 42, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (12, 'system:role:status', '修改角色状态', 'iam', 'POST', '/api/v1/system/roles/:id/status', 43, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (13, 'system:role:permission', '分配接口权限', 'iam', 'POST', '/api/v1/system/roles/:id/permissions', 44, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (14, 'system:role:menu', '分配菜单权限', 'iam', 'POST', '/api/v1/system/roles/:id/menus', 45, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (15, 'system:role:delete', '删除角色', 'iam', 'POST', '/api/v1/system/roles/:id/delete', 46, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (16, 'system:menu:list', '查看菜单', 'iam', 'GET', '/api/v1/system/menus', 50, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (17, 'system:menu:create', '创建菜单', 'iam', 'POST', '/api/v1/system/menus', 51, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (18, 'system:menu:update', '编辑菜单', 'iam', 'POST', '/api/v1/system/menus/:id/update', 52, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (19, 'system:menu:status', '修改菜单状态', 'iam', 'POST', '/api/v1/system/menus/:id/status', 53, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (20, 'system:menu:delete', '删除菜单', 'iam', 'POST', '/api/v1/system/menus/:id/delete', 54, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (21, 'system:department:list', '查看部门', 'iam', 'GET', '/api/v1/system/departments', 60, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (22, 'system:department:create', '创建部门', 'iam', 'POST', '/api/v1/system/departments', 61, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (23, 'system:department:update', '编辑部门', 'iam', 'POST', '/api/v1/system/departments/:id/update', 62, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (24, 'system:department:status', '修改部门状态', 'iam', 'POST', '/api/v1/system/departments/:id/status', 63, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (25, 'system:department:delete', '删除部门', 'iam', 'POST', '/api/v1/system/departments/:id/delete', 64, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (26, 'system:post:list', '查看岗位', 'iam', 'GET', '/api/v1/system/posts', 70, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (27, 'system:post:create', '创建岗位', 'iam', 'POST', '/api/v1/system/posts', 71, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (28, 'system:post:update', '编辑岗位', 'iam', 'POST', '/api/v1/system/posts/:id/update', 72, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (29, 'system:post:status', '修改岗位状态', 'iam', 'POST', '/api/v1/system/posts/:id/status', 73, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (30, 'system:post:delete', '删除岗位', 'iam', 'POST', '/api/v1/system/posts/:id/delete', 74, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (31, 'system:config:list', '查看配置', 'system', 'GET', '/api/v1/system/configs', 10, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (32, 'system:config:create', '创建配置', 'system', 'POST', '/api/v1/system/configs', 11, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (33, 'system:config:update', '编辑配置', 'system', 'POST', '/api/v1/system/configs/:id/update', 12, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (34, 'system:config:status', '修改配置状态', 'system', 'POST', '/api/v1/system/configs/:id/status', 13, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (35, 'system:config:delete', '删除配置', 'system', 'POST', '/api/v1/system/configs/:id/delete', 14, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (36, 'system:config:value', '读取配置值', 'system', 'GET', '/api/v1/system/configs/value/:key', 15, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (37, 'system:dict:type:list', '查看字典类型', 'system', 'GET', '/api/v1/system/dict-types', 20, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (38, 'system:dict:type:create', '创建字典类型', 'system', 'POST', '/api/v1/system/dict-types', 21, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (39, 'system:dict:type:update', '编辑字典类型', 'system', 'POST', '/api/v1/system/dict-types/:id/update', 22, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (40, 'system:dict:type:status', '修改字典类型状态', 'system', 'POST', '/api/v1/system/dict-types/:id/status', 23, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (41, 'system:dict:type:delete', '删除字典类型', 'system', 'POST', '/api/v1/system/dict-types/:id/delete', 24, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (42, 'system:dict:item:list', '查看字典项', 'system', 'GET', '/api/v1/system/dict-items', 25, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (43, 'system:dict:item:create', '创建字典项', 'system', 'POST', '/api/v1/system/dict-items', 26, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (44, 'system:dict:item:update', '编辑字典项', 'system', 'POST', '/api/v1/system/dict-items/:id/update', 27, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (45, 'system:dict:item:status', '修改字典项状态', 'system', 'POST', '/api/v1/system/dict-items/:id/status', 28, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (46, 'system:dict:item:delete', '删除字典项', 'system', 'POST', '/api/v1/system/dict-items/:id/delete', 29, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (47, 'system:file:list', '查看文件', 'system', 'GET', '/api/v1/system/files', 30, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (48, 'system:file:upload', '上传文件', 'system', 'POST', '/api/v1/system/files', 31, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (49, 'system:attachment:list', '查看附件', 'system', 'GET', '/api/v1/system/attachments', 40, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (50, 'system:attachment:upload', '上传附件', 'system', 'POST', '/api/v1/system/attachments', 41, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (51, 'system:attachment:update', '编辑附件', 'system', 'POST', '/api/v1/system/attachments/:id/update', 42, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (52, 'system:attachment:status', '修改附件状态', 'system', 'POST', '/api/v1/system/attachments/:id/status', 43, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (53, 'system:notice:list', '查看公告', 'system', 'GET', '/api/v1/system/notices', 50, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (54, 'system:notice:create', '创建公告', 'system', 'POST', '/api/v1/system/notices', 51, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (55, 'system:notice:update', '编辑公告', 'system', 'POST', '/api/v1/system/notices/:id/update', 52, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (56, 'system:notice:status', '修改公告状态', 'system', 'POST', '/api/v1/system/notices/:id/status', 53, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (57, 'system:notice:delete', '删除公告', 'system', 'POST', '/api/v1/system/notices/:id/delete', 54, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (58, 'system:operation-log:list', '查看操作日志', 'audit', 'GET', '/api/v1/system/operation-logs', 20, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (59, 'system:login-log:list', '查看登录日志', 'audit', 'GET', '/api/v1/system/login-logs', 30, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (60, 'system:notification:list', '查看通知', 'system', 'GET', '/api/v1/system/notifications', 60, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (61, 'system:notification:unread-count', '查看未读通知数', 'system', 'GET', '/api/v1/system/notifications/unread-count', 61, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (62, 'system:notification:mark-read', '标记通知已读', 'system', 'POST', '/api/v1/system/notifications/mark-read', 62, 1, '系统内置接口权限', NOW(3), NOW(3)),
  (63, 'system:notification:mark-all-read', '全部通知已读', 'system', 'POST', '/api/v1/system/notifications/mark-all-read', 63, 1, '系统内置接口权限', NOW(3), NOW(3));

INSERT INTO `sys_role_api` (`role_id`, `api_id`, `created_at`, `updated_at`)
SELECT 1, `id`, NOW(3), NOW(3)
FROM `sys_api`
WHERE `status` = 1
ORDER BY `id`;

INSERT INTO `casbin_rule` (`ptype`, `v0`, `v1`, `v2`)
SELECT 'p', 'super_admin', `path`, `method`
FROM `sys_api`
WHERE `status` = 1
ORDER BY `id`;

INSERT INTO `sys_role_menu` (`role_id`, `menu_id`, `created_at`, `updated_at`)
VALUES
  (1, 100, NOW(3), NOW(3)),
  (1, 101, NOW(3), NOW(3)),
  (1, 102, NOW(3), NOW(3)),
  (1, 211, NOW(3), NOW(3)),
  (1, 1110, NOW(3), NOW(3)),
  (1, 1111, NOW(3), NOW(3)),
  (1, 1112, NOW(3), NOW(3)),
  (1, 1113, NOW(3), NOW(3)),
  (1, 1114, NOW(3), NOW(3)),
  (1, 212, NOW(3), NOW(3)),
  (1, 1120, NOW(3), NOW(3)),
  (1, 1121, NOW(3), NOW(3)),
  (1, 1122, NOW(3), NOW(3)),
  (1, 1123, NOW(3), NOW(3)),
  (1, 1124, NOW(3), NOW(3)),
  (1, 201, NOW(3), NOW(3)),
  (1, 1010, NOW(3), NOW(3)),
  (1, 1011, NOW(3), NOW(3)),
  (1, 1012, NOW(3), NOW(3)),
  (1, 1013, NOW(3), NOW(3)),
  (1, 1014, NOW(3), NOW(3)),
  (1, 1015, NOW(3), NOW(3)),
  (1, 202, NOW(3), NOW(3)),
  (1, 1020, NOW(3), NOW(3)),
  (1, 1021, NOW(3), NOW(3)),
  (1, 1022, NOW(3), NOW(3)),
  (1, 1023, NOW(3), NOW(3)),
  (1, 1024, NOW(3), NOW(3)),
  (1, 1025, NOW(3), NOW(3)),
  (1, 1026, NOW(3), NOW(3)),
  (1, 203, NOW(3), NOW(3)),
  (1, 1030, NOW(3), NOW(3)),
  (1, 1031, NOW(3), NOW(3)),
  (1, 1032, NOW(3), NOW(3)),
  (1, 1033, NOW(3), NOW(3)),
  (1, 1034, NOW(3), NOW(3)),
  (1, 204, NOW(3), NOW(3)),
  (1, 1040, NOW(3), NOW(3)),
  (1, 1041, NOW(3), NOW(3)),
  (1, 1042, NOW(3), NOW(3)),
  (1, 1043, NOW(3), NOW(3)),
  (1, 1044, NOW(3), NOW(3)),
  (1, 1045, NOW(3), NOW(3)),
  (1, 209, NOW(3), NOW(3)),
  (1, 1090, NOW(3), NOW(3)),
  (1, 1091, NOW(3), NOW(3)),
  (1, 1092, NOW(3), NOW(3)),
  (1, 1093, NOW(3), NOW(3)),
  (1, 1098, NOW(3), NOW(3)),
  (1, 1094, NOW(3), NOW(3)),
  (1, 1095, NOW(3), NOW(3)),
  (1, 1096, NOW(3), NOW(3)),
  (1, 1097, NOW(3), NOW(3)),
  (1, 1099, NOW(3), NOW(3)),
  (1, 205, NOW(3), NOW(3)),
  (1, 1050, NOW(3), NOW(3)),
  (1, 1051, NOW(3), NOW(3)),
  (1, 210, NOW(3), NOW(3)),
  (1, 1100, NOW(3), NOW(3)),
  (1, 1101, NOW(3), NOW(3)),
  (1, 1102, NOW(3), NOW(3)),
  (1, 1103, NOW(3), NOW(3)),
  (1, 208, NOW(3), NOW(3)),
  (1, 1080, NOW(3), NOW(3)),
  (1, 1081, NOW(3), NOW(3)),
  (1, 1082, NOW(3), NOW(3)),
  (1, 1083, NOW(3), NOW(3)),
  (1, 1084, NOW(3), NOW(3)),
  (1, 200, NOW(3), NOW(3)),
  (1, 1001, NOW(3), NOW(3)),
  (1, 206, NOW(3), NOW(3)),
  (1, 1060, NOW(3), NOW(3)),
  (1, 207, NOW(3), NOW(3)),
  (1, 1070, NOW(3), NOW(3));

-- ============================================================================
-- Migration baseline
-- ============================================================================

CREATE TABLE IF NOT EXISTS `schema_migrations` (`version` BIGINT NOT NULL, `dirty` TINYINT(1) NOT NULL, PRIMARY KEY (`version`));
INSERT INTO `schema_migrations` (`version`, `dirty`) VALUES (1, 0)
ON DUPLICATE KEY UPDATE `dirty` = VALUES(`dirty`);
