import type { GlobalThemeOverrides } from 'naive-ui'

const fontFamily =
  'Inter, "PingFang SC", "Microsoft YaHei", system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif'

export const lightThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#2563FF',
    primaryColorHover: '#1D4ED8',
    primaryColorPressed: '#1E40AF',
    primaryColorSuppl: '#2563FF',
    successColor: '#12B981',
    warningColor: '#F59E0B',
    errorColor: '#EF4444',
    infoColor: '#0EA5E9',
    bodyColor: '#F6F8FB',
    cardColor: '#FFFFFF',
    modalColor: '#FFFFFF',
    popoverColor: '#FFFFFF',
    borderColor: '#E6ECF3',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    textColorBase: '#0F172A',
    textColor1: '#0F172A',
    textColor2: '#334155',
    textColor3: '#64748B',
    placeholderColor: '#94A3B8',
    fontFamily,
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '8px',
    heightMedium: '36px',
    heightSmall: '30px',
    fontWeight: '500',
  },
  Input: {
    borderRadius: '8px',
    heightMedium: '36px',
    heightSmall: '32px',
    borderFocus: '#2563FF',
    boxShadowFocus: '0 0 0 3px rgba(37, 99, 255, 0.12)',
  },
  Select: {
    peers: {
      InternalSelection: {
        borderRadius: '8px',
        heightMedium: '36px',
        heightSmall: '32px',
        borderFocus: '#2563FF',
        boxShadowFocus: '0 0 0 3px rgba(37, 99, 255, 0.12)',
      },
    },
  },
  Card: {
    borderRadius: '12px',
    paddingMedium: '20px',
    color: '#FFFFFF',
    borderColor: '#E6ECF3',
    boxShadow: '0 8px 24px rgba(15, 23, 42, 0.06)',
  },
  DataTable: {
    borderRadius: '10px',
    thColor: '#F8FAFC',
    thTextColor: '#334155',
    thFontWeight: '600',
    tdColor: '#FFFFFF',
    tdTextColor: '#0F172A',
    tdColorHover: '#F8FAFC',
    borderColor: '#E6ECF3',
  },
  Menu: {
    itemHeight: '42px',
    borderRadius: '8px',
    itemTextColorInverted: '#A8B3C5',
    itemTextColorHoverInverted: '#FFFFFF',
    itemTextColorActiveInverted: '#FFFFFF',
    itemTextColorActiveHoverInverted: '#FFFFFF',
    itemTextColorChildActiveInverted: '#FFFFFF',
    itemTextColorChildActiveHoverInverted: '#FFFFFF',
    itemIconColorInverted: '#A8B3C5',
    itemIconColorHoverInverted: '#FFFFFF',
    itemIconColorActiveInverted: '#FFFFFF',
    itemIconColorActiveHoverInverted: '#FFFFFF',
    itemIconColorChildActiveInverted: '#FFFFFF',
    itemIconColorChildActiveHoverInverted: '#FFFFFF',
    itemColorActiveInverted: '#2563FF',
    itemColorActiveHoverInverted: '#2563FF',
    itemColorActiveCollapsedInverted: '#2563FF',
    itemColorHoverInverted: 'rgba(37, 99, 255, 0.16)',
    arrowIconColorInverted: '#A8B3C5',
  },
  Layout: {
    headerBorderColor: '#E6ECF3',
  },
  Tabs: {
    tabFontWeightActive: '600',
    tabTextColorActiveLine: '#2563FF',
    tabTextColorHoverLine: '#2563FF',
    barColor: '#2563FF',
  },
  Drawer: {
    borderRadius: '12px',
  },
  Modal: {
    borderRadius: '12px',
  },
  Dropdown: {
    borderRadius: '10px',
    boxShadow: '0 12px 32px rgba(15, 23, 42, 0.12)',
  },
  Tag: {
    borderRadius: '6px',
  },
}

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#3B82F6',
    primaryColorHover: '#60A5FA',
    primaryColorPressed: '#2563EB',
    primaryColorSuppl: '#3B82F6',
    successColor: '#12B981',
    warningColor: '#F59E0B',
    errorColor: '#EF4444',
    infoColor: '#0EA5E9',
    bodyColor: '#0B1120',
    cardColor: '#111827',
    modalColor: '#111827',
    popoverColor: '#111827',
    borderColor: 'rgba(148, 163, 184, 0.16)',
    borderRadius: '8px',
    borderRadiusSmall: '6px',
    textColorBase: '#E5E7EB',
    textColor1: '#E5E7EB',
    textColor2: '#CBD5E1',
    textColor3: '#94A3B8',
    placeholderColor: '#64748B',
    fontFamily,
  },
  Button: {
    borderRadiusMedium: '8px',
    borderRadiusSmall: '8px',
    heightMedium: '36px',
    heightSmall: '30px',
    fontWeight: '500',
  },
  Input: {
    borderRadius: '8px',
    heightMedium: '36px',
    heightSmall: '32px',
    color: '#111827',
    textColor: '#E5E7EB',
    borderFocus: '#3B82F6',
    boxShadowFocus: '0 0 0 3px rgba(59, 130, 246, 0.14)',
  },
  Select: {
    peers: {
      InternalSelection: {
        borderRadius: '8px',
        heightMedium: '36px',
        heightSmall: '32px',
        color: '#111827',
        textColor: '#E5E7EB',
        borderFocus: '#3B82F6',
        boxShadowFocus: '0 0 0 3px rgba(59, 130, 246, 0.14)',
      },
    },
  },
  Card: {
    borderRadius: '12px',
    paddingMedium: '20px',
    color: '#111827',
    borderColor: 'rgba(148, 163, 184, 0.16)',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.24)',
  },
  DataTable: {
    borderRadius: '10px',
    thColor: '#0F172A',
    thTextColor: '#CBD5E1',
    thFontWeight: '600',
    tdColor: '#111827',
    tdTextColor: '#E5E7EB',
    tdColorHover: '#172033',
    borderColor: 'rgba(148, 163, 184, 0.16)',
  },
  Menu: lightThemeOverrides.Menu,
  Layout: {
    headerBorderColor: 'rgba(148, 163, 184, 0.16)',
    color: '#0B1120',
  },
  Tabs: {
    tabFontWeightActive: '600',
    tabTextColorActiveLine: '#60A5FA',
    tabTextColorHoverLine: '#60A5FA',
    barColor: '#3B82F6',
  },
  Drawer: {
    borderRadius: '12px',
  },
  Modal: {
    borderRadius: '12px',
  },
  Dropdown: {
    borderRadius: '10px',
    boxShadow: '0 12px 32px rgba(0, 0, 0, 0.35)',
  },
  Tag: {
    borderRadius: '6px',
  },
}
