/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/account": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.AccountProfileResponse"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/auth/account/password": {
    post: {
      parameters: {
        body: {
          /** 密码参数 */
          body: definitions["api.UpdateAccountPasswordRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/auth/account/profile": {
    post: {
      parameters: {
        body: {
          /** 更新参数 */
          body: definitions["api.UpdateAccountProfileRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.AccountProfileResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/auth/dashboard": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.DashboardResponse"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/auth/login": {
    post: {
      parameters: {
        body: {
          /** 登录参数 */
          body: definitions["api.LoginRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.LoginResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Internal Server Error */
        500: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/auth/logout": {
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/auth/me": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.MeResponse"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/auth/menus": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.MenuResponse"][];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/auth/refresh": {
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.LoginResponse"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/setup/init": {
    /** 使用默认账号创建超级管理员，仅当系统中无用户时可执行。 */
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["setup.initResponse"];
        };
        /** Conflict */
        409: {
          schema: { [key: string]: unknown };
        };
        /** Internal Server Error */
        500: {
          schema: { [key: string]: unknown };
        };
      };
    };
  };
  "/system/attachments": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 关键词 */
          keyword?: string;
          /** 附件分类 */
          category?: string;
          /** 业务类型 */
          biz_type?: string;
          /** 文件后缀 */
          ext?: string;
          /** 状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_attachment_api.ListResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        formData: {
          /** 附件文件 */
          file: unknown;
          /** 附件名称 */
          display_name?: string;
          /** 附件分类 */
          category?: string;
          /** 业务类型 */
          biz_type?: string;
          /** 状态 */
          status?: number;
          /** 备注 */
          remark?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_attachment_api.Response"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/attachments/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 附件 ID */
          id: number;
        };
        body: {
          /** 状态参数 */
          body: definitions["ez-admin-gin_server_internal_modules_system_attachment_api.UpdateStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/attachments/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 附件 ID */
          id: number;
        };
        body: {
          /** 附件参数 */
          body: definitions["ez-admin-gin_server_internal_modules_system_attachment_api.UpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_attachment_api.Response"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/configs": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 关键词 */
          keyword?: string;
          /** 配置分组 */
          group_code?: string;
          /** 状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_config_api.ListResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 配置参数 */
          body: definitions["ez-admin-gin_server_internal_modules_system_config_api.CreateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_config_api.Response"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/configs/value/{key}": {
    get: {
      parameters: {
        path: {
          /** 配置键 */
          key: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.ValueResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/configs/{id}/delete": {
    post: {
      parameters: {
        path: {
          /** 配置 ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/configs/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 配置 ID */
          id: number;
        };
        body: {
          /** 状态参数 */
          body: definitions["ez-admin-gin_server_internal_modules_system_config_api.UpdateStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/configs/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 配置 ID */
          id: number;
        };
        body: {
          /** 配置参数 */
          body: definitions["ez-admin-gin_server_internal_modules_system_config_api.UpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_config_api.Response"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/departments": {
    get: {
      parameters: {
        query: {
          /** 关键词 */
          keyword?: string;
          /** 状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 部门信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_department_api.CreateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/departments/{id}/delete": {
    post: {
      parameters: {
        path: {
          /** 部门 ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/departments/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 部门 ID */
          id: number;
        };
        body: {
          /** 状态 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_department_api.UpdateStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/departments/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 部门 ID */
          id: number;
        };
        body: {
          /** 部门信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_department_api.UpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/dict-items": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 字典类型 ID */
          type_id: number;
          /** 关键词 */
          keyword?: string;
          /** 状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.ItemListResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 字典项参数 */
          body: definitions["api.CreateItemRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.ItemResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/dict-items/{id}/delete": {
    post: {
      parameters: {
        path: {
          /** 字典项 ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/dict-items/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 字典项 ID */
          id: number;
        };
        body: {
          /** 状态参数 */
          body: definitions["api.UpdateItemStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/dict-items/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 字典项 ID */
          id: number;
        };
        body: {
          /** 字典项参数 */
          body: definitions["api.UpdateItemRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.ItemResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/dict-types": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 关键词 */
          keyword?: string;
          /** 状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.TypeListResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 字典类型参数 */
          body: definitions["api.CreateTypeRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.TypeResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/dict-types/{id}/delete": {
    post: {
      parameters: {
        path: {
          /** 字典类型 ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/dict-types/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 字典类型 ID */
          id: number;
        };
        body: {
          /** 状态参数 */
          body: definitions["api.UpdateTypeStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/dict-types/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 字典类型 ID */
          id: number;
        };
        body: {
          /** 字典类型参数 */
          body: definitions["api.UpdateTypeRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.TypeResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/files": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 关键词 */
          keyword?: string;
          /** 文件后缀 */
          ext?: string;
          /** 状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_file_api.ListResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        formData: {
          /** 文件 */
          file: unknown;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_file_api.Response"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/login-logs": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 用户名 */
          username?: string;
          /** IP 地址 */
          ip?: string;
          /** 登录状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_loginlog_api.ListResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/menus": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 菜单信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_menu_api.CreateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/menus/{id}/delete": {
    post: {
      parameters: {
        path: {
          /** 菜单 ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/menus/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 菜单 ID */
          id: number;
        };
        body: {
          /** 状态 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_menu_api.UpdateStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/menus/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 菜单 ID */
          id: number;
        };
        body: {
          /** 菜单信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_menu_api.UpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/notices": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 关键词 */
          keyword?: string;
          /** 状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_notice_api.ListResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 公告参数 */
          body: definitions["ez-admin-gin_server_internal_modules_system_notice_api.CreateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_notice_api.Response"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/notices/{id}/delete": {
    post: {
      parameters: {
        path: {
          /** 公告 ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/notices/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 公告 ID */
          id: number;
        };
        body: {
          /** 状态参数 */
          body: definitions["ez-admin-gin_server_internal_modules_system_notice_api.UpdateStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/notices/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 公告 ID */
          id: number;
        };
        body: {
          /** 公告参数 */
          body: definitions["ez-admin-gin_server_internal_modules_system_notice_api.UpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_notice_api.Response"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/notifications": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 通知类型 */
          type?: number;
          /** 已读状态 0=全部 1=未读 2=已读 */
          is_read?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_notification_api.ListResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/notifications/mark-all-read": {
    post: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/notifications/mark-read": {
    post: {
      parameters: {
        body: {
          /** 通知 ID 列表 */
          body: definitions["api.MarkReadRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/notifications/unread-count": {
    get: {
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["api.UnreadCountResponse"];
          };
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/operation-logs": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 用户名 */
          username?: string;
          /** 请求方法 */
          method?: string;
          /** 请求路径 */
          path?: string;
          /** 是否成功，支持 true/false/1/0 */
          success?: string;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"] & {
            data?: definitions["ez-admin-gin_server_internal_modules_system_operationlog_api.ListResponse"];
          };
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/posts": {
    get: {
      parameters: {
        query: {
          /** 关键词 */
          keyword?: string;
          /** 状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 岗位信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_post_api.CreateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/posts/{id}/delete": {
    post: {
      parameters: {
        path: {
          /** 岗位 ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/posts/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 岗位 ID */
          id: number;
        };
        body: {
          /** 状态 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_post_api.UpdateStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/posts/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 岗位 ID */
          id: number;
        };
        body: {
          /** 岗位信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_post_api.UpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/roles": {
    get: {
      parameters: {
        query: {
          /** 关键词 */
          keyword?: string;
          /** 状态 */
          status?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 角色信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_role_api.CreateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/roles/{id}/delete": {
    post: {
      parameters: {
        path: {
          /** 角色 ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/roles/{id}/menus": {
    post: {
      parameters: {
        path: {
          /** 角色 ID */
          id: number;
        };
        body: {
          /** 菜单 ID 列表 */
          body: definitions["api.UpdateMenusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/roles/{id}/permissions": {
    post: {
      parameters: {
        path: {
          /** 角色 ID */
          id: number;
        };
        body: {
          /** 权限列表 */
          body: definitions["api.UpdatePermissionsRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/roles/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 角色 ID */
          id: number;
        };
        body: {
          /** 状态 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_role_api.UpdateStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/roles/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 角色 ID */
          id: number;
        };
        body: {
          /** 角色信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_role_api.UpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/users": {
    get: {
      parameters: {
        query: {
          /** 页码 */
          page?: number;
          /** 每页条数 */
          page_size?: number;
          /** 关键词 */
          keyword?: string;
          /** 状态 */
          status?: number;
          /** 部门 ID */
          department_id?: number;
          /** 角色 ID */
          role_id?: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
    post: {
      parameters: {
        body: {
          /** 用户信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_user_api.CreateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/users/{id}/delete": {
    post: {
      parameters: {
        path: {
          /** 用户 ID */
          id: number;
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/users/{id}/roles": {
    post: {
      parameters: {
        path: {
          /** 用户 ID */
          id: number;
        };
        body: {
          /** 角色 ID 列表 */
          body: definitions["api.UpdateRolesRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/users/{id}/status": {
    post: {
      parameters: {
        path: {
          /** 用户 ID */
          id: number;
        };
        body: {
          /** 状态 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_user_api.UpdateStatusRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
  "/system/users/{id}/update": {
    post: {
      parameters: {
        path: {
          /** 用户 ID */
          id: number;
        };
        body: {
          /** 用户信息 */
          body: definitions["ez-admin-gin_server_internal_modules_iam_user_api.UpdateRequest"];
        };
      };
      responses: {
        /** OK */
        200: {
          schema: definitions["httpx.Body"];
        };
        /** Bad Request */
        400: {
          schema: definitions["httpx.Body"];
        };
        /** Unauthorized */
        401: {
          schema: definitions["httpx.Body"];
        };
      };
    };
  };
}

export interface definitions {
  "api.AccountProfileResponse": {
    data_scope?: definitions["domain.MeDataScopeResult"];
    department_id?: number;
    department_name?: string;
    is_super_admin?: boolean;
    nickname?: string;
    role_codes?: string[];
    status?: definitions["model.UserStatus"];
    updated_at?: string;
    user_id?: number;
    username?: string;
  };
  "api.CreateItemRequest": {
    item_key?: string;
    label?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemDictStatus"];
    tag_type?: string;
    type_id?: number;
    value?: string;
  };
  "api.CreateTypeRequest": {
    code?: string;
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemDictStatus"];
  };
  "api.DashboardResponse": {
    current_user?: definitions["domain.DashboardCurrentUser"];
    health?: definitions["domain.DashboardHealth"];
    latest_notices?: definitions["domain.DashboardNoticeItem"][];
    metrics?: definitions["domain.DashboardMetrics"];
    recent_logins?: definitions["domain.DashboardLoginItem"][];
    recent_operations?: definitions["domain.DashboardOperationItem"][];
  };
  "api.ItemListResponse": {
    items?: definitions["domain.ItemResponse"][];
    page?: number;
    page_size?: number;
    total?: number;
  };
  "api.ItemResponse": {
    created_at?: string;
    id?: number;
    item_key?: string;
    label?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemDictStatus"];
    tag_type?: string;
    type_id?: number;
    updated_at?: string;
    value?: string;
  };
  "api.LoginRequest": {
    password: string;
    username: string;
  };
  "api.LoginResponse": {
    access_token?: string;
    expires_at?: string;
    nickname?: string;
    token_type?: string;
    user_id?: number;
    username?: string;
  };
  "api.MarkReadRequest": {
    ids?: number[];
  };
  "api.MeResponse": {
    data_scope?: definitions["domain.MeDataScopeResult"];
    department_id?: number;
    is_super_admin?: boolean;
    role_codes?: string[];
    user_id?: number;
    username?: string;
  };
  "api.MenuResponse": {
    children?: definitions["domain.MenuResponse"][];
    code?: string;
    component?: string;
    icon?: string;
    id?: number;
    parent_id?: number;
    path?: string;
    sort?: number;
    title?: string;
    type?: definitions["model.MenuType"];
  };
  "api.TypeListResponse": {
    items?: definitions["domain.TypeResponse"][];
    page?: number;
    page_size?: number;
    total?: number;
  };
  "api.TypeResponse": {
    code?: string;
    created_at?: string;
    id?: number;
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemDictStatus"];
    updated_at?: string;
  };
  "api.UnreadCountResponse": {
    count?: number;
  };
  "api.UpdateAccountPasswordRequest": {
    new_password?: string;
    old_password?: string;
  };
  "api.UpdateAccountProfileRequest": {
    nickname?: string;
  };
  "api.UpdateItemRequest": {
    label?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemDictStatus"];
    tag_type?: string;
    value?: string;
  };
  "api.UpdateItemStatusRequest": {
    status?: definitions["model.SystemDictStatus"];
  };
  "api.UpdateMenusRequest": {
    menu_ids?: number[];
  };
  "api.UpdatePermissionsRequest": {
    permissions?: definitions["domain.PermissionItem"][];
  };
  "api.UpdateRolesRequest": {
    role_ids?: number[];
  };
  "api.UpdateTypeRequest": {
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemDictStatus"];
  };
  "api.UpdateTypeStatusRequest": {
    status?: definitions["model.SystemDictStatus"];
  };
  "api.ValueResponse": {
    key?: string;
    source?: string;
    value?: string;
  };
  /** @enum {string} */
  "datascope.Scope":
    | "all"
    | "dept"
    | "dept_and_children"
    | "self"
    | "custom_dept";
  "domain.DashboardCurrentUser": {
    nickname?: string;
    user_id?: number;
    username?: string;
  };
  "domain.DashboardHealth": {
    database?: string;
    env?: string;
    redis?: string;
  };
  "domain.DashboardLoginItem": {
    created_at?: string;
    id?: number;
    ip?: string;
    message?: string;
    status?: definitions["model.LoginLogStatus"];
    username?: string;
  };
  "domain.DashboardMetrics": {
    config_total?: number;
    enabled_role_total?: number;
    enabled_user_total?: number;
    file_total?: number;
    notice_total?: number;
    today_login_failed_total?: number;
    today_operation_total?: number;
    today_risk_operation_total?: number;
    user_total?: number;
  };
  "domain.DashboardNoticeItem": {
    id?: number;
    status?: definitions["model.NoticeStatus"];
    title?: string;
    updated_at?: string;
  };
  "domain.DashboardOperationItem": {
    created_at?: string;
    id?: number;
    latency_ms?: number;
    method?: string;
    path?: string;
    status_code?: number;
    success?: boolean;
    username?: string;
  };
  "domain.ItemResponse": {
    created_at?: string;
    id?: number;
    item_key?: string;
    label?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemDictStatus"];
    tag_type?: string;
    type_id?: number;
    updated_at?: string;
    value?: string;
  };
  "domain.MeDataScopeResult": {
    allow_all?: boolean;
    custom_department_ids?: number[];
    include_department?: boolean;
    include_dept_tree?: boolean;
    require_self?: boolean;
  };
  "domain.MenuResponse": {
    children?: definitions["domain.MenuResponse"][];
    code?: string;
    component?: string;
    icon?: string;
    id?: number;
    parent_id?: number;
    path?: string;
    sort?: number;
    title?: string;
    type?: definitions["model.MenuType"];
  };
  "domain.PermissionItem": {
    method?: string;
    path?: string;
  };
  "domain.TypeResponse": {
    code?: string;
    created_at?: string;
    id?: number;
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemDictStatus"];
    updated_at?: string;
  };
  /** @enum {integer} */
  "errorsx.Code": 0 | 40000 | 40100 | 40300 | 40400 | 42900 | 50300 | 50000;
  "ez-admin-gin_server_internal_modules_iam_department_api.CreateRequest": {
    code?: string;
    leader_user_id?: number | null;
    name?: string;
    parent_id?: number;
    remark?: string;
    sort?: number;
    status?: definitions["model.DepartmentStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_department_api.UpdateRequest": {
    code?: string;
    leader_user_id?: number | null;
    name?: string;
    parent_id?: number;
    remark?: string;
    sort?: number;
    status?: definitions["model.DepartmentStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_department_api.UpdateStatusRequest": {
    status?: definitions["model.DepartmentStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_menu_api.CreateRequest": {
    code?: string;
    component?: string;
    icon?: string;
    parent_id?: number;
    path?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.MenuStatus"];
    title?: string;
    type?: definitions["model.MenuType"];
  };
  "ez-admin-gin_server_internal_modules_iam_menu_api.UpdateRequest": {
    component?: string;
    icon?: string;
    parent_id?: number;
    path?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.MenuStatus"];
    title?: string;
    type?: definitions["model.MenuType"];
  };
  "ez-admin-gin_server_internal_modules_iam_menu_api.UpdateStatusRequest": {
    status?: definitions["model.MenuStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_post_api.CreateRequest": {
    code?: string;
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.PostStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_post_api.UpdateRequest": {
    code?: string;
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.PostStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_post_api.UpdateStatusRequest": {
    status?: definitions["model.PostStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_role_api.CreateRequest": {
    code?: string;
    custom_department_ids?: number[];
    data_scope?: definitions["datascope.Scope"];
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.RoleStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_role_api.UpdateRequest": {
    custom_department_ids?: number[];
    data_scope?: definitions["datascope.Scope"];
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.RoleStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_role_api.UpdateStatusRequest": {
    status?: definitions["model.RoleStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_user_api.CreateRequest": {
    department_id?: number;
    nickname?: string;
    password?: string;
    post_ids?: number[];
    role_ids?: number[];
    status?: definitions["model.UserStatus"];
    username?: string;
  };
  "ez-admin-gin_server_internal_modules_iam_user_api.UpdateRequest": {
    department_id?: number;
    nickname?: string;
    post_ids?: number[];
    status?: definitions["model.UserStatus"];
  };
  "ez-admin-gin_server_internal_modules_iam_user_api.UpdateStatusRequest": {
    status?: definitions["model.UserStatus"];
  };
  "ez-admin-gin_server_internal_modules_system_attachment_api.ListResponse": {
    items?: definitions["ez-admin-gin_server_internal_modules_system_attachment_domain.Response"][];
    page?: number;
    page_size?: number;
    total?: number;
  };
  "ez-admin-gin_server_internal_modules_system_attachment_api.Response": {
    biz_type?: string;
    category?: string;
    created_at?: string;
    display_name?: string;
    ext?: string;
    file_id?: number;
    file_name?: string;
    id?: number;
    mime_type?: string;
    original_name?: string;
    remark?: string;
    size?: number;
    status?: definitions["model.SystemAttachmentStatus"];
    updated_at?: string;
    uploader_id?: number;
    url?: string;
  };
  "ez-admin-gin_server_internal_modules_system_attachment_api.UpdateRequest": {
    biz_type?: string;
    category?: string;
    display_name?: string;
    remark?: string;
    status?: definitions["model.SystemAttachmentStatus"];
  };
  "ez-admin-gin_server_internal_modules_system_attachment_api.UpdateStatusRequest": {
    status?: definitions["model.SystemAttachmentStatus"];
  };
  "ez-admin-gin_server_internal_modules_system_attachment_domain.Response": {
    biz_type?: string;
    category?: string;
    created_at?: string;
    display_name?: string;
    ext?: string;
    file_id?: number;
    file_name?: string;
    id?: number;
    mime_type?: string;
    original_name?: string;
    remark?: string;
    size?: number;
    status?: definitions["model.SystemAttachmentStatus"];
    updated_at?: string;
    uploader_id?: number;
    url?: string;
  };
  "ez-admin-gin_server_internal_modules_system_config_api.CreateRequest": {
    group_code?: string;
    key?: string;
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemConfigStatus"];
    value?: string;
  };
  "ez-admin-gin_server_internal_modules_system_config_api.ListResponse": {
    items?: definitions["ez-admin-gin_server_internal_modules_system_config_domain.Response"][];
    page?: number;
    page_size?: number;
    total?: number;
  };
  "ez-admin-gin_server_internal_modules_system_config_api.Response": {
    created_at?: string;
    group_code?: string;
    id?: number;
    key?: string;
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemConfigStatus"];
    updated_at?: string;
    value?: string;
  };
  "ez-admin-gin_server_internal_modules_system_config_api.UpdateRequest": {
    group_code?: string;
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemConfigStatus"];
    value?: string;
  };
  "ez-admin-gin_server_internal_modules_system_config_api.UpdateStatusRequest": {
    status?: definitions["model.SystemConfigStatus"];
  };
  "ez-admin-gin_server_internal_modules_system_config_domain.Response": {
    created_at?: string;
    group_code?: string;
    id?: number;
    key?: string;
    name?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.SystemConfigStatus"];
    updated_at?: string;
    value?: string;
  };
  "ez-admin-gin_server_internal_modules_system_file_api.ListResponse": {
    items?: definitions["ez-admin-gin_server_internal_modules_system_file_domain.Response"][];
    page?: number;
    page_size?: number;
    total?: number;
  };
  "ez-admin-gin_server_internal_modules_system_file_api.Response": {
    created_at?: string;
    ext?: string;
    file_name?: string;
    id?: number;
    mime_type?: string;
    original_name?: string;
    path?: string;
    remark?: string;
    sha256?: string;
    size?: number;
    status?: definitions["model.SystemFileStatus"];
    storage?: string;
    updated_at?: string;
    uploader_id?: number;
    url?: string;
  };
  "ez-admin-gin_server_internal_modules_system_file_domain.Response": {
    created_at?: string;
    ext?: string;
    file_name?: string;
    id?: number;
    mime_type?: string;
    original_name?: string;
    path?: string;
    remark?: string;
    sha256?: string;
    size?: number;
    status?: definitions["model.SystemFileStatus"];
    storage?: string;
    updated_at?: string;
    uploader_id?: number;
    url?: string;
  };
  "ez-admin-gin_server_internal_modules_system_loginlog_api.ListResponse": {
    items?: definitions["ez-admin-gin_server_internal_modules_system_loginlog_domain.Response"][];
    page?: number;
    page_size?: number;
    total?: number;
  };
  "ez-admin-gin_server_internal_modules_system_loginlog_domain.Response": {
    created_at?: string;
    id?: number;
    ip?: string;
    message?: string;
    status?: definitions["model.LoginLogStatus"];
    user_agent?: string;
    user_id?: number;
    username?: string;
  };
  "ez-admin-gin_server_internal_modules_system_notice_api.CreateRequest": {
    content?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.NoticeStatus"];
    title?: string;
  };
  "ez-admin-gin_server_internal_modules_system_notice_api.ListResponse": {
    items?: definitions["ez-admin-gin_server_internal_modules_system_notice_domain.Response"][];
    page?: number;
    page_size?: number;
    total?: number;
  };
  "ez-admin-gin_server_internal_modules_system_notice_api.Response": {
    content?: string;
    created_at?: string;
    id?: number;
    remark?: string;
    sort?: number;
    status?: definitions["model.NoticeStatus"];
    title?: string;
    updated_at?: string;
  };
  "ez-admin-gin_server_internal_modules_system_notice_api.UpdateRequest": {
    content?: string;
    remark?: string;
    sort?: number;
    status?: definitions["model.NoticeStatus"];
    title?: string;
  };
  "ez-admin-gin_server_internal_modules_system_notice_api.UpdateStatusRequest": {
    status?: definitions["model.NoticeStatus"];
  };
  "ez-admin-gin_server_internal_modules_system_notice_domain.Response": {
    content?: string;
    created_at?: string;
    id?: number;
    remark?: string;
    sort?: number;
    status?: definitions["model.NoticeStatus"];
    title?: string;
    updated_at?: string;
  };
  "ez-admin-gin_server_internal_modules_system_notification_api.ListResponse": {
    items?: definitions["ez-admin-gin_server_internal_modules_system_notification_domain.Response"][];
    page?: number;
    page_size?: number;
    total?: number;
  };
  "ez-admin-gin_server_internal_modules_system_notification_domain.Response": {
    content?: string;
    created_at?: string;
    extra?: definitions["model.JSONMap"];
    id?: number;
    is_read?: boolean;
    read_at?: string;
    title?: string;
    type?: definitions["model.NotificationType"];
  };
  "ez-admin-gin_server_internal_modules_system_operationlog_api.ListResponse": {
    items?: definitions["ez-admin-gin_server_internal_modules_system_operationlog_domain.Response"][];
    page?: number;
    page_size?: number;
    total?: number;
  };
  "ez-admin-gin_server_internal_modules_system_operationlog_domain.Response": {
    created_at?: string;
    error_message?: string;
    id?: number;
    ip?: string;
    latency_ms?: number;
    method?: string;
    path?: string;
    query?: string;
    route_path?: string;
    status_code?: number;
    success?: boolean;
    user_agent?: string;
    user_id?: number;
    username?: string;
  };
  "httpx.Body": {
    code?: definitions["errorsx.Code"];
    data?: unknown;
    message?: string;
  };
  /** @enum {integer} */
  "model.DepartmentStatus": 1 | 2;
  "model.JSONMap": { [key: string]: unknown };
  /** @enum {integer} */
  "model.LoginLogStatus": 1 | 2;
  /** @enum {integer} */
  "model.MenuStatus": 1 | 2;
  /** @enum {integer} */
  "model.MenuType": 1 | 2 | 3;
  /** @enum {integer} */
  "model.NoticeStatus": 1 | 2;
  /** @enum {integer} */
  "model.NotificationType": 1 | 2 | 3 | 4;
  /** @enum {integer} */
  "model.PostStatus": 1 | 2;
  /** @enum {integer} */
  "model.RoleStatus": 1 | 2;
  /** @enum {integer} */
  "model.SystemAttachmentStatus": 1 | 2;
  /** @enum {integer} */
  "model.SystemConfigStatus": 1 | 2;
  /** @enum {integer} */
  "model.SystemDictStatus": 1 | 2;
  /** @enum {integer} */
  "model.SystemFileStatus": 1 | 2;
  /** @enum {integer} */
  "model.UserStatus": 1 | 2;
  "setup.initResponse": {
    message?: string;
    user_id?: number;
    username?: string;
  };
}

export interface operations {}

export interface external {}
