-- Stable full initialization SQL for postgres.
-- Generated by scripts/build-full-migrations.sh.
--
-- Covers final schema + built-in seed data.
-- Does NOT create the first admin user.
-- Create the first admin with POST /api/v1/setup/init after import.

-- ============================================================================
-- Final schema
-- ============================================================================

-- 系统用户表
CREATE TABLE sys_user (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) NOT NULL DEFAULT '',
  department_id BIGINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_user_username ON sys_user (username);
CREATE INDEX idx_sys_user_department_id ON sys_user (department_id);
CREATE INDEX idx_sys_user_deleted_at ON sys_user (deleted_at);

COMMENT ON TABLE sys_user IS '后台用户表';
COMMENT ON COLUMN sys_user.id IS '用户记录主键，数据库自增生成';
COMMENT ON COLUMN sys_user.username IS '登录用户名';
COMMENT ON COLUMN sys_user.password_hash IS '密码哈希';
COMMENT ON COLUMN sys_user.nickname IS '管理台展示名称';
COMMENT ON COLUMN sys_user.department_id IS '部门 ID，对应 sys_department.id';
COMMENT ON COLUMN sys_user.status IS '用户状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_user.created_at IS '创建时间';
COMMENT ON COLUMN sys_user.updated_at IS '更新时间';
COMMENT ON COLUMN sys_user.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 系统角色表
CREATE TABLE sys_role (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  data_scope VARCHAR(32) NOT NULL DEFAULT 'self',
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_role_code ON sys_role (code);
CREATE INDEX idx_sys_role_status ON sys_role (status);
CREATE INDEX idx_sys_role_deleted_at ON sys_role (deleted_at);

COMMENT ON TABLE sys_role IS '后台角色表';
COMMENT ON COLUMN sys_role.id IS '角色记录主键，数据库自增生成';
COMMENT ON COLUMN sys_role.code IS '角色编码';
COMMENT ON COLUMN sys_role.name IS '角色名称';
COMMENT ON COLUMN sys_role.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_role.data_scope IS '数据权限范围：all/dept/dept_and_children/self/custom_dept';
COMMENT ON COLUMN sys_role.status IS '角色状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_role.remark IS '备注';
COMMENT ON COLUMN sys_role.created_at IS '创建时间';
COMMENT ON COLUMN sys_role.updated_at IS '更新时间';
COMMENT ON COLUMN sys_role.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 用户角色关系表
CREATE TABLE sys_user_role (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_sys_user_role_user_role ON sys_user_role (user_id, role_id);
CREATE INDEX idx_sys_user_role_user_id ON sys_user_role (user_id);
CREATE INDEX idx_sys_user_role_role_id ON sys_user_role (role_id);

COMMENT ON TABLE sys_user_role IS '用户角色关系表';
COMMENT ON COLUMN sys_user_role.id IS '关系记录主键，数据库自增生成';
COMMENT ON COLUMN sys_user_role.user_id IS '用户 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_user_role.role_id IS '角色 ID，对应 sys_role.id';
COMMENT ON COLUMN sys_user_role.created_at IS '绑定时间';
COMMENT ON COLUMN sys_user_role.updated_at IS '更新时间';

-- 系统菜单和按钮表
CREATE TABLE sys_menu (
  id BIGSERIAL PRIMARY KEY,
  parent_id BIGINT NOT NULL DEFAULT 0,
  type SMALLINT NOT NULL,
  code VARCHAR(128) NOT NULL,
  title VARCHAR(64) NOT NULL,
  path VARCHAR(255) NOT NULL DEFAULT '',
  component VARCHAR(255) NOT NULL DEFAULT '',
  icon VARCHAR(64) NOT NULL DEFAULT '',
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_menu_code ON sys_menu (code);
CREATE INDEX idx_sys_menu_parent_id ON sys_menu (parent_id);
CREATE INDEX idx_sys_menu_type ON sys_menu (type);
CREATE INDEX idx_sys_menu_status ON sys_menu (status);
CREATE INDEX idx_sys_menu_deleted_at ON sys_menu (deleted_at);

COMMENT ON TABLE sys_menu IS '后台菜单和按钮表';
COMMENT ON COLUMN sys_menu.id IS '菜单记录主键，数据库自增生成';
COMMENT ON COLUMN sys_menu.parent_id IS '父级菜单 ID，根节点为 0';
COMMENT ON COLUMN sys_menu.type IS '节点类型：1 目录，2 菜单，3 按钮';
COMMENT ON COLUMN sys_menu.code IS '菜单或按钮编码，系统内唯一';
COMMENT ON COLUMN sys_menu.title IS '展示名称';
COMMENT ON COLUMN sys_menu.path IS '前端路由路径';
COMMENT ON COLUMN sys_menu.component IS '前端组件路径';
COMMENT ON COLUMN sys_menu.icon IS '图标标识';
COMMENT ON COLUMN sys_menu.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_menu.status IS '菜单状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_menu.remark IS '备注';
COMMENT ON COLUMN sys_menu.created_at IS '创建时间';
COMMENT ON COLUMN sys_menu.updated_at IS '更新时间';
COMMENT ON COLUMN sys_menu.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 角色菜单关系表
CREATE TABLE sys_role_menu (
  id BIGSERIAL PRIMARY KEY,
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_sys_role_menu_role_menu ON sys_role_menu (role_id, menu_id);
CREATE INDEX idx_sys_role_menu_role_id ON sys_role_menu (role_id);
CREATE INDEX idx_sys_role_menu_menu_id ON sys_role_menu (menu_id);

COMMENT ON TABLE sys_role_menu IS '角色菜单关系表';
COMMENT ON COLUMN sys_role_menu.id IS '关系记录主键，数据库自增生成';
COMMENT ON COLUMN sys_role_menu.role_id IS '角色 ID，对应 sys_role.id';
COMMENT ON COLUMN sys_role_menu.menu_id IS '菜单 ID，对应 sys_menu.id';
COMMENT ON COLUMN sys_role_menu.created_at IS '绑定时间';
COMMENT ON COLUMN sys_role_menu.updated_at IS '更新时间';

-- 接口权限元数据表
CREATE TABLE sys_api (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(128) NOT NULL,
  name VARCHAR(64) NOT NULL,
  module VARCHAR(64) NOT NULL DEFAULT '',
  method VARCHAR(16) NOT NULL,
  path VARCHAR(255) NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_api_code ON sys_api (code);
CREATE UNIQUE INDEX uk_sys_api_method_path ON sys_api (method, path);
CREATE INDEX idx_sys_api_module ON sys_api (module);
CREATE INDEX idx_sys_api_status ON sys_api (status);
CREATE INDEX idx_sys_api_deleted_at ON sys_api (deleted_at);

COMMENT ON TABLE sys_api IS '接口权限元数据表';
COMMENT ON COLUMN sys_api.id IS '接口权限记录主键，数据库自增生成';
COMMENT ON COLUMN sys_api.code IS '接口权限编码，系统内唯一';
COMMENT ON COLUMN sys_api.name IS '接口权限名称';
COMMENT ON COLUMN sys_api.module IS '所属模块，例如 iam、system、audit';
COMMENT ON COLUMN sys_api.method IS 'HTTP 方法';
COMMENT ON COLUMN sys_api.path IS '接口路径模式';
COMMENT ON COLUMN sys_api.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_api.status IS '接口权限状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_api.remark IS '备注';
COMMENT ON COLUMN sys_api.created_at IS '创建时间';
COMMENT ON COLUMN sys_api.updated_at IS '更新时间';
COMMENT ON COLUMN sys_api.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 角色接口权限关系表
CREATE TABLE sys_role_api (
  id BIGSERIAL PRIMARY KEY,
  role_id BIGINT NOT NULL,
  api_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_sys_role_api_role_api ON sys_role_api (role_id, api_id);
CREATE INDEX idx_sys_role_api_role_id ON sys_role_api (role_id);
CREATE INDEX idx_sys_role_api_api_id ON sys_role_api (api_id);

COMMENT ON TABLE sys_role_api IS '角色接口权限关系表';
COMMENT ON COLUMN sys_role_api.id IS '关系记录主键，数据库自增生成';
COMMENT ON COLUMN sys_role_api.role_id IS '角色 ID，对应 sys_role.id';
COMMENT ON COLUMN sys_role_api.api_id IS '接口权限 ID，对应 sys_api.id';
COMMENT ON COLUMN sys_role_api.created_at IS '绑定时间';
COMMENT ON COLUMN sys_role_api.updated_at IS '更新时间';

-- 系统配置表
CREATE TABLE sys_config (
  id BIGSERIAL PRIMARY KEY,
  group_code VARCHAR(64) NOT NULL,
  config_key VARCHAR(128) NOT NULL,
  name VARCHAR(64) NOT NULL,
  value TEXT NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_config_key ON sys_config (config_key);
CREATE INDEX idx_sys_config_group_code ON sys_config (group_code);
CREATE INDEX idx_sys_config_status ON sys_config (status);
CREATE INDEX idx_sys_config_deleted_at ON sys_config (deleted_at);

COMMENT ON TABLE sys_config IS '系统配置表';
COMMENT ON COLUMN sys_config.id IS '配置记录主键，数据库自增生成';
COMMENT ON COLUMN sys_config.group_code IS '配置分组，例如 site、upload';
COMMENT ON COLUMN sys_config.config_key IS '配置键，系统内唯一，例如 site:title';
COMMENT ON COLUMN sys_config.name IS '配置名称';
COMMENT ON COLUMN sys_config.value IS '配置值，统一按字符串存储';
COMMENT ON COLUMN sys_config.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_config.status IS '配置状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_config.remark IS '备注';
COMMENT ON COLUMN sys_config.created_at IS '创建时间';
COMMENT ON COLUMN sys_config.updated_at IS '更新时间';
COMMENT ON COLUMN sys_config.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 文件上传记录表
CREATE TABLE sys_file (
  id BIGSERIAL PRIMARY KEY,
  storage VARCHAR(32) NOT NULL DEFAULT 'local',
  original_name VARCHAR(255) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  ext VARCHAR(32) NOT NULL DEFAULT '',
  mime_type VARCHAR(128) NOT NULL DEFAULT '',
  size BIGINT NOT NULL DEFAULT 0,
  sha256 VARCHAR(64) NOT NULL DEFAULT '',
  path VARCHAR(500) NOT NULL,
  url VARCHAR(500) NOT NULL,
  uploader_id BIGINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_sys_file_ext ON sys_file (ext);
CREATE INDEX idx_sys_file_sha256 ON sys_file (sha256);
CREATE INDEX idx_sys_file_uploader_id ON sys_file (uploader_id);
CREATE INDEX idx_sys_file_status ON sys_file (status);
CREATE INDEX idx_sys_file_deleted_at ON sys_file (deleted_at);

COMMENT ON TABLE sys_file IS '文件上传记录表';
COMMENT ON COLUMN sys_file.id IS '文件记录主键，数据库自增生成';
COMMENT ON COLUMN sys_file.storage IS '存储类型，本节使用 local';
COMMENT ON COLUMN sys_file.original_name IS '用户上传时的原始文件名';
COMMENT ON COLUMN sys_file.file_name IS '后端生成的保存文件名';
COMMENT ON COLUMN sys_file.ext IS '文件后缀，例如 .png、.pdf';
COMMENT ON COLUMN sys_file.mime_type IS '上传请求中的文件 MIME 类型';
COMMENT ON COLUMN sys_file.size IS '文件大小，单位字节';
COMMENT ON COLUMN sys_file.sha256 IS '文件内容 SHA-256 哈希';
COMMENT ON COLUMN sys_file.path IS '服务端保存路径';
COMMENT ON COLUMN sys_file.url IS '前端可访问地址';
COMMENT ON COLUMN sys_file.uploader_id IS '上传用户 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_file.status IS '文件状态：1 启用，2 停用';
COMMENT ON COLUMN sys_file.remark IS '备注';
COMMENT ON COLUMN sys_file.created_at IS '创建时间';
COMMENT ON COLUMN sys_file.updated_at IS '更新时间';
COMMENT ON COLUMN sys_file.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 操作日志表
CREATE TABLE sys_operation_log (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL DEFAULT 0,
  username VARCHAR(64) NOT NULL DEFAULT '',
  method VARCHAR(10) NOT NULL,
  path VARCHAR(255) NOT NULL,
  route_path VARCHAR(255) NOT NULL DEFAULT '',
  query VARCHAR(1000) NOT NULL DEFAULT '',
  ip VARCHAR(64) NOT NULL DEFAULT '',
  user_agent VARCHAR(500) NOT NULL DEFAULT '',
  status_code INTEGER NOT NULL DEFAULT 0,
  latency_ms BIGINT NOT NULL DEFAULT 0,
  success BOOLEAN NOT NULL DEFAULT TRUE,
  error_message VARCHAR(500) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_sys_operation_log_user_id ON sys_operation_log (user_id);
CREATE INDEX idx_sys_operation_log_username ON sys_operation_log (username);
CREATE INDEX idx_sys_operation_log_method ON sys_operation_log (method);
CREATE INDEX idx_sys_operation_log_path ON sys_operation_log (path);
CREATE INDEX idx_sys_operation_log_route_path ON sys_operation_log (route_path);
CREATE INDEX idx_sys_operation_log_status_code ON sys_operation_log (status_code);
CREATE INDEX idx_sys_operation_log_success ON sys_operation_log (success);
CREATE INDEX idx_sys_operation_log_created_at ON sys_operation_log (created_at);

COMMENT ON TABLE sys_operation_log IS '操作日志表';
COMMENT ON COLUMN sys_operation_log.id IS '操作日志主键，数据库自增生成';
COMMENT ON COLUMN sys_operation_log.user_id IS '操作人 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_operation_log.username IS '操作人用户名';
COMMENT ON COLUMN sys_operation_log.method IS 'HTTP 请求方法';
COMMENT ON COLUMN sys_operation_log.path IS '实际请求路径';
COMMENT ON COLUMN sys_operation_log.route_path IS 'Gin 路由模板';
COMMENT ON COLUMN sys_operation_log.query IS '查询参数';
COMMENT ON COLUMN sys_operation_log.ip IS '客户端 IP';
COMMENT ON COLUMN sys_operation_log.user_agent IS '浏览器或客户端标识';
COMMENT ON COLUMN sys_operation_log.status_code IS 'HTTP 状态码';
COMMENT ON COLUMN sys_operation_log.latency_ms IS '请求耗时，单位毫秒';
COMMENT ON COLUMN sys_operation_log.success IS '是否成功';
COMMENT ON COLUMN sys_operation_log.error_message IS '错误摘要';
COMMENT ON COLUMN sys_operation_log.created_at IS '创建时间';

-- 登录日志表
CREATE TABLE sys_login_log (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL DEFAULT 0,
  username VARCHAR(64) NOT NULL DEFAULT '',
  status SMALLINT NOT NULL,
  message VARCHAR(255) NOT NULL DEFAULT '',
  ip VARCHAR(64) NOT NULL DEFAULT '',
  user_agent VARCHAR(500) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_sys_login_log_user_id ON sys_login_log (user_id);
CREATE INDEX idx_sys_login_log_username ON sys_login_log (username);
CREATE INDEX idx_sys_login_log_status ON sys_login_log (status);
CREATE INDEX idx_sys_login_log_ip ON sys_login_log (ip);
CREATE INDEX idx_sys_login_log_created_at ON sys_login_log (created_at);

COMMENT ON TABLE sys_login_log IS '登录日志表';
COMMENT ON COLUMN sys_login_log.id IS '登录日志主键，数据库自增生成';
COMMENT ON COLUMN sys_login_log.user_id IS '用户 ID，对应 sys_user.id；用户名不存在时为 0';
COMMENT ON COLUMN sys_login_log.username IS '登录用户名';
COMMENT ON COLUMN sys_login_log.status IS '登录状态：1 成功，2 失败';
COMMENT ON COLUMN sys_login_log.message IS '登录结果说明';
COMMENT ON COLUMN sys_login_log.ip IS '客户端 IP';
COMMENT ON COLUMN sys_login_log.user_agent IS '浏览器或客户端标识';
COMMENT ON COLUMN sys_login_log.created_at IS '创建时间';

-- 公告表
CREATE TABLE sys_notice (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  content TEXT NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_sys_notice_deleted_at ON sys_notice (deleted_at);

COMMENT ON TABLE sys_notice IS '公告表';
COMMENT ON COLUMN sys_notice.id IS '公告记录主键，数据库自增生成';
COMMENT ON COLUMN sys_notice.title IS '公告标题';
COMMENT ON COLUMN sys_notice.content IS '公告内容';
COMMENT ON COLUMN sys_notice.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_notice.status IS '公告状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_notice.remark IS '备注';
COMMENT ON COLUMN sys_notice.created_at IS '创建时间';
COMMENT ON COLUMN sys_notice.updated_at IS '更新时间';
COMMENT ON COLUMN sys_notice.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 消息模板表
CREATE TABLE sys_message_template (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(128) NOT NULL,
  name VARCHAR(64) NOT NULL,
  title VARCHAR(128) NOT NULL,
  content TEXT NOT NULL,
  type SMALLINT NOT NULL DEFAULT 1,
  variables TEXT NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  is_system BOOLEAN NOT NULL DEFAULT TRUE,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_message_template_code ON sys_message_template (code);
CREATE INDEX idx_sys_message_template_type ON sys_message_template (type);
CREATE INDEX idx_sys_message_template_status ON sys_message_template (status);
CREATE INDEX idx_sys_message_template_deleted_at ON sys_message_template (deleted_at);

COMMENT ON TABLE sys_message_template IS '消息模板表';
COMMENT ON COLUMN sys_message_template.id IS '消息模板主键，数据库自增生成';
COMMENT ON COLUMN sys_message_template.code IS '模板编码，系统内唯一';
COMMENT ON COLUMN sys_message_template.name IS '模板名称';
COMMENT ON COLUMN sys_message_template.title IS '消息标题模板';
COMMENT ON COLUMN sys_message_template.content IS '消息内容模板';
COMMENT ON COLUMN sys_message_template.type IS '模板类型：1 站内通知，2 待办提醒，3 告警提醒';
COMMENT ON COLUMN sys_message_template.variables IS '模板变量说明';
COMMENT ON COLUMN sys_message_template.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_message_template.status IS '配置状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_message_template.is_system IS '是否系统级配置';
COMMENT ON COLUMN sys_message_template.remark IS '备注';
COMMENT ON COLUMN sys_message_template.created_at IS '创建时间';
COMMENT ON COLUMN sys_message_template.updated_at IS '更新时间';
COMMENT ON COLUMN sys_message_template.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 消息提醒规则表
CREATE TABLE sys_message_reminder (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(128) NOT NULL,
  name VARCHAR(64) NOT NULL,
  trigger_event VARCHAR(128) NOT NULL,
  template_id BIGINT NOT NULL,
  channels VARCHAR(128) NOT NULL DEFAULT 'notification',
  receiver_type SMALLINT NOT NULL DEFAULT 1,
  receiver_values TEXT NOT NULL,
  advance_minutes INTEGER NOT NULL DEFAULT 0,
  link_url VARCHAR(255) NOT NULL DEFAULT '',
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  is_system BOOLEAN NOT NULL DEFAULT TRUE,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_message_reminder_code ON sys_message_reminder (code);
CREATE INDEX idx_sys_message_reminder_trigger_event ON sys_message_reminder (trigger_event);
CREATE INDEX idx_sys_message_reminder_template_id ON sys_message_reminder (template_id);
CREATE INDEX idx_sys_message_reminder_receiver_type ON sys_message_reminder (receiver_type);
CREATE INDEX idx_sys_message_reminder_status ON sys_message_reminder (status);
CREATE INDEX idx_sys_message_reminder_deleted_at ON sys_message_reminder (deleted_at);

COMMENT ON TABLE sys_message_reminder IS '消息提醒规则表';
COMMENT ON COLUMN sys_message_reminder.id IS '提醒规则主键，数据库自增生成';
COMMENT ON COLUMN sys_message_reminder.code IS '提醒编码，系统内唯一';
COMMENT ON COLUMN sys_message_reminder.name IS '提醒名称';
COMMENT ON COLUMN sys_message_reminder.trigger_event IS '触发事件编码，例如 auth:login:success';
COMMENT ON COLUMN sys_message_reminder.template_id IS '消息模板 ID，对应 sys_message_template.id';
COMMENT ON COLUMN sys_message_reminder.channels IS '提醒渠道，多个渠道用英文逗号分隔';
COMMENT ON COLUMN sys_message_reminder.receiver_type IS '接收人类型：1 角色，2 用户，3 部门，4 发起人，5 负责人';
COMMENT ON COLUMN sys_message_reminder.receiver_values IS '接收人配置值，按接收人类型保存角色编码、用户 ID 或部门 ID';
COMMENT ON COLUMN sys_message_reminder.advance_minutes IS '提前提醒分钟数，0 表示即时提醒';
COMMENT ON COLUMN sys_message_reminder.link_url IS '消息跳转链接';
COMMENT ON COLUMN sys_message_reminder.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_message_reminder.status IS '配置状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_message_reminder.is_system IS '是否系统级配置';
COMMENT ON COLUMN sys_message_reminder.remark IS '备注';
COMMENT ON COLUMN sys_message_reminder.created_at IS '创建时间';
COMMENT ON COLUMN sys_message_reminder.updated_at IS '更新时间';
COMMENT ON COLUMN sys_message_reminder.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 系统邮箱账号表
CREATE TABLE sys_mail_account (
  id BIGSERIAL PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  host VARCHAR(128) NOT NULL,
  port INTEGER NOT NULL DEFAULT 25,
  username VARCHAR(128) NOT NULL DEFAULT '',
  password VARCHAR(255) NOT NULL DEFAULT '',
  from_email VARCHAR(128) NOT NULL,
  from_name VARCHAR(64) NOT NULL DEFAULT '',
  encryption VARCHAR(16) NOT NULL DEFAULT 'none',
  is_default BOOLEAN NOT NULL DEFAULT FALSE,
  status SMALLINT NOT NULL DEFAULT 1,
  last_test_at TIMESTAMPTZ NULL,
  last_test_msg VARCHAR(255) NOT NULL DEFAULT '',
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_mail_account_name ON sys_mail_account (name);
CREATE INDEX idx_sys_mail_account_default ON sys_mail_account (is_default);
CREATE INDEX idx_sys_mail_account_status ON sys_mail_account (status);
CREATE INDEX idx_sys_mail_account_deleted_at ON sys_mail_account (deleted_at);

COMMENT ON TABLE sys_mail_account IS '系统邮箱账号表';
COMMENT ON COLUMN sys_mail_account.id IS '邮箱账号主键，数据库自增生成';
COMMENT ON COLUMN sys_mail_account.name IS '邮箱账号名称';
COMMENT ON COLUMN sys_mail_account.host IS 'SMTP 主机';
COMMENT ON COLUMN sys_mail_account.port IS 'SMTP 端口';
COMMENT ON COLUMN sys_mail_account.username IS 'SMTP 登录用户名';
COMMENT ON COLUMN sys_mail_account.password IS 'SMTP 登录密码或授权码';
COMMENT ON COLUMN sys_mail_account.from_email IS '发件邮箱';
COMMENT ON COLUMN sys_mail_account.from_name IS '发件人名称';
COMMENT ON COLUMN sys_mail_account.encryption IS '加密方式：none、ssl、starttls';
COMMENT ON COLUMN sys_mail_account.is_default IS '是否默认发信账号';
COMMENT ON COLUMN sys_mail_account.status IS '邮箱状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_mail_account.last_test_at IS '最近一次测试时间';
COMMENT ON COLUMN sys_mail_account.last_test_msg IS '最近一次测试结果';
COMMENT ON COLUMN sys_mail_account.remark IS '备注';
COMMENT ON COLUMN sys_mail_account.created_at IS '创建时间';
COMMENT ON COLUMN sys_mail_account.updated_at IS '更新时间';
COMMENT ON COLUMN sys_mail_account.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 邮件模板表
CREATE TABLE sys_mail_template (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  subject VARCHAR(200) NOT NULL,
  content TEXT NOT NULL,
  is_html BOOLEAN NOT NULL DEFAULT TRUE,
  variables TEXT NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_mail_template_code ON sys_mail_template (code);
CREATE INDEX idx_sys_mail_template_status ON sys_mail_template (status);
CREATE INDEX idx_sys_mail_template_deleted_at ON sys_mail_template (deleted_at);

COMMENT ON TABLE sys_mail_template IS '邮件模板表';
COMMENT ON COLUMN sys_mail_template.id IS '邮件模板主键，数据库自增生成';
COMMENT ON COLUMN sys_mail_template.code IS '模板编码，系统内唯一';
COMMENT ON COLUMN sys_mail_template.name IS '模板名称';
COMMENT ON COLUMN sys_mail_template.subject IS '邮件主题模板';
COMMENT ON COLUMN sys_mail_template.content IS '邮件正文模板';
COMMENT ON COLUMN sys_mail_template.is_html IS '是否 HTML 邮件';
COMMENT ON COLUMN sys_mail_template.variables IS '模板变量 JSON 数组';
COMMENT ON COLUMN sys_mail_template.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_mail_template.status IS '模板状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_mail_template.remark IS '备注';
COMMENT ON COLUMN sys_mail_template.created_at IS '创建时间';
COMMENT ON COLUMN sys_mail_template.updated_at IS '更新时间';
COMMENT ON COLUMN sys_mail_template.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 邮件发送日志表
CREATE TABLE sys_mail_log (
  id BIGSERIAL PRIMARY KEY,
  account_id BIGINT NOT NULL DEFAULT 0,
  account_name VARCHAR(64) NOT NULL DEFAULT '',
  template_id BIGINT NOT NULL DEFAULT 0,
  template_code VARCHAR(64) NOT NULL DEFAULT '',
  subject VARCHAR(200) NOT NULL DEFAULT '',
  from_email VARCHAR(128) NOT NULL DEFAULT '',
  to_emails TEXT NOT NULL,
  cc_emails TEXT NOT NULL,
  bcc_emails TEXT NOT NULL,
  status SMALLINT NOT NULL,
  error_message VARCHAR(500) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_sys_mail_log_account_id ON sys_mail_log (account_id);
CREATE INDEX idx_sys_mail_log_template_id ON sys_mail_log (template_id);
CREATE INDEX idx_sys_mail_log_template_code ON sys_mail_log (template_code);
CREATE INDEX idx_sys_mail_log_status ON sys_mail_log (status);
CREATE INDEX idx_sys_mail_log_created_at ON sys_mail_log (created_at);

COMMENT ON TABLE sys_mail_log IS '邮件发送日志表';
COMMENT ON COLUMN sys_mail_log.id IS '邮件发送日志主键，数据库自增生成';
COMMENT ON COLUMN sys_mail_log.account_id IS '邮箱账号 ID，对应 sys_mail_account.id';
COMMENT ON COLUMN sys_mail_log.account_name IS '邮箱账号快照名称';
COMMENT ON COLUMN sys_mail_log.template_id IS '邮件模板 ID，对应 sys_mail_template.id';
COMMENT ON COLUMN sys_mail_log.template_code IS '邮件模板编码快照';
COMMENT ON COLUMN sys_mail_log.subject IS '邮件主题快照';
COMMENT ON COLUMN sys_mail_log.from_email IS '发件邮箱快照';
COMMENT ON COLUMN sys_mail_log.to_emails IS '收件人邮箱，逗号分隔';
COMMENT ON COLUMN sys_mail_log.cc_emails IS '抄送邮箱，逗号分隔';
COMMENT ON COLUMN sys_mail_log.bcc_emails IS '密送邮箱，逗号分隔';
COMMENT ON COLUMN sys_mail_log.status IS '发送状态：1 成功，2 失败';
COMMENT ON COLUMN sys_mail_log.error_message IS '失败错误摘要';
COMMENT ON COLUMN sys_mail_log.created_at IS '创建时间';

-- Casbin 权限策略表
CREATE TABLE casbin_rule (
  id BIGSERIAL PRIMARY KEY,
  ptype VARCHAR(100) NOT NULL DEFAULT '',
  v0 VARCHAR(100) NOT NULL DEFAULT '',
  v1 VARCHAR(100) NOT NULL DEFAULT '',
  v2 VARCHAR(100) NOT NULL DEFAULT '',
  v3 VARCHAR(100) NOT NULL DEFAULT '',
  v4 VARCHAR(100) NOT NULL DEFAULT '',
  v5 VARCHAR(100) NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX uk_casbin_rule_policy ON casbin_rule (ptype, v0, v1, v2, v3, v4, v5);
CREATE INDEX idx_casbin_rule_ptype ON casbin_rule (ptype);
CREATE INDEX idx_casbin_rule_subject ON casbin_rule (v0);

COMMENT ON TABLE casbin_rule IS 'Casbin 权限策略表';
COMMENT ON COLUMN casbin_rule.id IS '策略记录主键，数据库自增生成';
COMMENT ON COLUMN casbin_rule.ptype IS '策略类型，例如 p';
COMMENT ON COLUMN casbin_rule.v0 IS '策略主体，本项目存角色编码';
COMMENT ON COLUMN casbin_rule.v1 IS '资源路径';
COMMENT ON COLUMN casbin_rule.v2 IS '请求方法';
COMMENT ON COLUMN casbin_rule.v3 IS '预留字段';
COMMENT ON COLUMN casbin_rule.v4 IS '预留字段';
COMMENT ON COLUMN casbin_rule.v5 IS '预留字段';

CREATE TABLE sys_department (
  id BIGSERIAL PRIMARY KEY,
  parent_id BIGINT NOT NULL DEFAULT 0,
  ancestors VARCHAR(500) NOT NULL DEFAULT '',
  name VARCHAR(64) NOT NULL,
  code VARCHAR(64) NOT NULL,
  leader_user_id BIGINT NULL DEFAULT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_department_code
ON sys_department (code);

CREATE INDEX idx_sys_department_parent_id
ON sys_department (parent_id);

CREATE INDEX idx_sys_department_leader_user_id
ON sys_department (leader_user_id);

CREATE INDEX idx_sys_department_status
ON sys_department (status);

CREATE INDEX idx_sys_department_deleted_at
ON sys_department (deleted_at);

COMMENT ON TABLE sys_department IS '组织部门表';
COMMENT ON COLUMN sys_department.parent_id IS '父部门 ID，根节点为 0';
COMMENT ON COLUMN sys_department.ancestors IS '祖先路径，例如 0,1,3';
COMMENT ON COLUMN sys_department.name IS '部门名称';
COMMENT ON COLUMN sys_department.code IS '部门编码';
COMMENT ON COLUMN sys_department.leader_user_id IS '负责人用户 ID，未设置时为 NULL';
COMMENT ON COLUMN sys_department.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_department.status IS '部门状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_department.remark IS '备注';

CREATE TABLE sys_post (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_post_code
ON sys_post (code);

CREATE INDEX idx_sys_post_status
ON sys_post (status);

CREATE INDEX idx_sys_post_deleted_at
ON sys_post (deleted_at);

COMMENT ON TABLE sys_post IS '岗位表';
COMMENT ON COLUMN sys_post.code IS '岗位编码';
COMMENT ON COLUMN sys_post.name IS '岗位名称';
COMMENT ON COLUMN sys_post.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_post.status IS '岗位状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_post.remark IS '备注';

CREATE TABLE sys_user_post (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_sys_user_post_user_post
ON sys_user_post (user_id, post_id);

CREATE INDEX idx_sys_user_post_user_id
ON sys_user_post (user_id);

CREATE INDEX idx_sys_user_post_post_id
ON sys_user_post (post_id);

COMMENT ON TABLE sys_user_post IS '用户岗位关系表';
COMMENT ON COLUMN sys_user_post.user_id IS '用户 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_user_post.post_id IS '岗位 ID，对应 sys_post.id';

CREATE TABLE sys_role_data_scope (
  id BIGSERIAL PRIMARY KEY,
  role_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_sys_role_data_scope_role_department
ON sys_role_data_scope (role_id, department_id);

CREATE INDEX idx_sys_role_data_scope_role_id
ON sys_role_data_scope (role_id);

CREATE INDEX idx_sys_role_data_scope_department_id
ON sys_role_data_scope (department_id);

COMMENT ON TABLE sys_role_data_scope IS '角色自定义部门数据范围关系表';
COMMENT ON COLUMN sys_role_data_scope.role_id IS '角色 ID，对应 sys_role.id';
COMMENT ON COLUMN sys_role_data_scope.department_id IS '部门 ID，对应 sys_department.id';

CREATE TABLE sys_dict_type (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_dict_type_code ON sys_dict_type (code);
CREATE INDEX idx_sys_dict_type_status ON sys_dict_type (status);
CREATE INDEX idx_sys_dict_type_deleted_at ON sys_dict_type (deleted_at);

COMMENT ON TABLE sys_dict_type IS '系统字典类型表';
COMMENT ON COLUMN sys_dict_type.id IS '字典类型主键，数据库自增生成';
COMMENT ON COLUMN sys_dict_type.code IS '字典编码，系统内唯一';
COMMENT ON COLUMN sys_dict_type.name IS '字典名称';
COMMENT ON COLUMN sys_dict_type.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_dict_type.status IS '字典状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_dict_type.remark IS '备注';
COMMENT ON COLUMN sys_dict_type.created_at IS '创建时间';
COMMENT ON COLUMN sys_dict_type.updated_at IS '更新时间';
COMMENT ON COLUMN sys_dict_type.deleted_at IS '逻辑删除时间，NULL 表示未删除';

CREATE TABLE sys_dict_item (
  id BIGSERIAL PRIMARY KEY,
  type_id BIGINT NOT NULL,
  item_key VARCHAR(64) NOT NULL,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(255) NOT NULL,
  tag_type VARCHAR(32) NOT NULL DEFAULT '',
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_dict_item_type_key ON sys_dict_item (type_id, item_key);
CREATE INDEX idx_sys_dict_item_type_id ON sys_dict_item (type_id);
CREATE INDEX idx_sys_dict_item_status ON sys_dict_item (status);
CREATE INDEX idx_sys_dict_item_deleted_at ON sys_dict_item (deleted_at);

COMMENT ON TABLE sys_dict_item IS '系统字典项表';
COMMENT ON COLUMN sys_dict_item.id IS '字典项主键，数据库自增生成';
COMMENT ON COLUMN sys_dict_item.type_id IS '字典类型 ID，对应 sys_dict_type.id';
COMMENT ON COLUMN sys_dict_item.item_key IS '字典项编码，同一类型内唯一';
COMMENT ON COLUMN sys_dict_item.label IS '字典项名称';
COMMENT ON COLUMN sys_dict_item.value IS '字典项值';
COMMENT ON COLUMN sys_dict_item.tag_type IS '前端标签样式提示';
COMMENT ON COLUMN sys_dict_item.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_dict_item.status IS '字典项状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_dict_item.remark IS '备注';
COMMENT ON COLUMN sys_dict_item.created_at IS '创建时间';
COMMENT ON COLUMN sys_dict_item.updated_at IS '更新时间';
COMMENT ON COLUMN sys_dict_item.deleted_at IS '逻辑删除时间，NULL 表示未删除';

CREATE TABLE sys_attachment (
  id BIGSERIAL PRIMARY KEY,
  file_id BIGINT NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT '',
  biz_type VARCHAR(64) NOT NULL DEFAULT '',
  uploader_id BIGINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_attachment_file_id ON sys_attachment (file_id);
CREATE INDEX idx_sys_attachment_category ON sys_attachment (category);
CREATE INDEX idx_sys_attachment_biz_type ON sys_attachment (biz_type);
CREATE INDEX idx_sys_attachment_uploader_id ON sys_attachment (uploader_id);
CREATE INDEX idx_sys_attachment_status ON sys_attachment (status);
CREATE INDEX idx_sys_attachment_deleted_at ON sys_attachment (deleted_at);

COMMENT ON TABLE sys_attachment IS '附件中心表';
COMMENT ON COLUMN sys_attachment.id IS '附件记录主键，数据库自增生成';
COMMENT ON COLUMN sys_attachment.file_id IS '底层文件记录 ID，对应 sys_file.id';
COMMENT ON COLUMN sys_attachment.display_name IS '附件展示名，默认使用原始文件名';
COMMENT ON COLUMN sys_attachment.category IS '附件分类，例如 invoice、contract、avatar';
COMMENT ON COLUMN sys_attachment.biz_type IS '业务类型，用于区分模块接入来源';
COMMENT ON COLUMN sys_attachment.uploader_id IS '上传用户 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_attachment.status IS '附件状态：1 启用，2 停用';
COMMENT ON COLUMN sys_attachment.remark IS '备注';
COMMENT ON COLUMN sys_attachment.created_at IS '创建时间';
COMMENT ON COLUMN sys_attachment.updated_at IS '更新时间';
COMMENT ON COLUMN sys_attachment.deleted_at IS '逻辑删除时间，NULL 表示未删除';

CREATE TABLE sys_notification (
    id         BIGSERIAL PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    type       SMALLINT NOT NULL DEFAULT 1,
    title      VARCHAR(128) NOT NULL DEFAULT '',
    content    TEXT NOT NULL DEFAULT '',
    extra      JSONB,
    is_read    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    read_at    TIMESTAMP
);

CREATE INDEX idx_notification_user_unread ON sys_notification(user_id, is_read, created_at DESC);

-- ============================================================================
-- Built-in seed data
-- ============================================================================

INSERT INTO sys_role (id, code, name, sort, data_scope, status, remark, created_at, updated_at)
VALUES
  (1, 'super_admin', '超级管理员', 0, 'all', 1, '系统内置角色', NOW(), NOW());

INSERT INTO sys_config (id, group_code, config_key, name, value, sort, status, remark, created_at, updated_at)
VALUES
  (1, 'rate_limit', 'rate_limit:login_max_requests', '登录 IP 限流次数', '200', 10, 1, '登录接口每 IP 在窗口期内最大请求数，启用后实时生效', NOW(), NOW()),
  (2, 'rate_limit', 'rate_limit:login_window_sec', '登录 IP 限流窗口秒数', '60', 20, 1, '登录接口 IP 限流滑动窗口，启用后实时生效', NOW(), NOW()),
  (3, 'rate_limit', 'rate_limit:login_lockout_threshold', '账号锁定失败次数', '5', 30, 1, '账号连续登录失败达到该次数后进入锁定，启用后实时生效', NOW(), NOW()),
  (4, 'rate_limit', 'rate_limit:login_lockout_sec', '账号锁定秒数', '300', 40, 1, '账号登录失败锁定持续时间，启用后实时生效', NOW(), NOW()),
  (5, 'upload', 'upload:max_size_mb', '单文件大小上限 MB', '10', 10, 1, '文件与附件上传大小限制，启用后实时生效', NOW(), NOW()),
  (6, 'upload', 'upload:allowed_exts', '允许上传扩展名', '.jpg,.jpeg,.png,.gif,.webp,.pdf,.txt,.docx,.xlsx', 20, 1, '文件与附件上传扩展名白名单，启用后实时生效', NOW(), NOW());

INSERT INTO sys_menu (id, parent_id, type, code, title, path, component, icon, sort, status, remark, created_at, updated_at)
VALUES
  (100, 0, 1, 'iam', '权限管理', '/iam', '', 'shield', 20, 1, '系统内置目录', NOW(), NOW()),
  (101, 0, 1, 'system', '系统设置', '/system', '', 'setting', 30, 1, '系统内置目录', NOW(), NOW()),
  (102, 0, 1, 'audit', '审计监控', '/audit', '', 'analytics', 40, 1, '系统内置目录', NOW(), NOW()),
  (211, 100, 2, 'system:department', '部门管理', '/iam/departments', 'iam/DepartmentView', 'git-branch', 10, 1, '系统内置菜单', NOW(), NOW()),
  (1110, 211, 3, 'system:department:list', '查看部门', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1111, 211, 3, 'system:department:create', '创建部门', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1112, 211, 3, 'system:department:update', '编辑部门', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1113, 211, 3, 'system:department:status', '修改部门状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1114, 211, 3, 'system:department:delete', '删除部门', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (212, 100, 2, 'system:post', '岗位管理', '/iam/posts', 'iam/PostView', 'briefcase', 20, 1, '系统内置菜单', NOW(), NOW()),
  (1120, 212, 3, 'system:post:list', '查看岗位', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1121, 212, 3, 'system:post:create', '创建岗位', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1122, 212, 3, 'system:post:update', '编辑岗位', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1123, 212, 3, 'system:post:status', '修改岗位状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1124, 212, 3, 'system:post:delete', '删除岗位', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (201, 100, 2, 'system:user', '用户管理', '/iam/users', 'iam/UserView', 'people', 30, 1, '系统内置菜单', NOW(), NOW()),
  (1010, 201, 3, 'system:user:list', '查看用户', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1011, 201, 3, 'system:user:create', '创建用户', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1012, 201, 3, 'system:user:update', '编辑用户', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1013, 201, 3, 'system:user:status', '修改用户状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1014, 201, 3, 'system:user:assign-role', '分配用户角色', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (1015, 201, 3, 'system:user:delete', '删除用户', '', '', '', 60, 1, '系统内置按钮', NOW(), NOW()),
  (202, 100, 2, 'system:role', '角色管理', '/iam/roles', 'iam/RoleView', 'shield', 40, 1, '系统内置菜单', NOW(), NOW()),
  (1020, 202, 3, 'system:role:list', '查看角色', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1021, 202, 3, 'system:role:create', '创建角色', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1022, 202, 3, 'system:role:update', '编辑角色', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1023, 202, 3, 'system:role:status', '修改角色状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1024, 202, 3, 'system:role:permission', '分配接口权限', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (1025, 202, 3, 'system:role:menu', '分配菜单权限', '', '', '', 60, 1, '系统内置按钮', NOW(), NOW()),
  (1026, 202, 3, 'system:role:delete', '删除角色', '', '', '', 70, 1, '系统内置按钮', NOW(), NOW()),
  (203, 100, 2, 'system:menu', '菜单管理', '/iam/menus', 'iam/MenuView', 'layers', 50, 1, '系统内置菜单', NOW(), NOW()),
  (1030, 203, 3, 'system:menu:list', '查看菜单', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1031, 203, 3, 'system:menu:create', '创建菜单', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1032, 203, 3, 'system:menu:update', '编辑菜单', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1033, 203, 3, 'system:menu:status', '修改菜单状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1034, 203, 3, 'system:menu:delete', '删除菜单', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (204, 101, 2, 'system:config', '系统配置', '/system/configs', 'system/ConfigView', 'cog', 10, 1, '系统内置菜单', NOW(), NOW()),
  (1040, 204, 3, 'system:config:list', '查看配置', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1041, 204, 3, 'system:config:create', '创建配置', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1042, 204, 3, 'system:config:update', '编辑配置', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1043, 204, 3, 'system:config:status', '修改配置状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1044, 204, 3, 'system:config:value', '读取配置值', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (1045, 204, 3, 'system:config:delete', '删除配置', '', '', '', 60, 1, '系统内置按钮', NOW(), NOW()),
  (209, 101, 2, 'system:dict', '数据字典', '/system/dicts', 'system/DictView', 'albums', 20, 1, '系统内置菜单', NOW(), NOW()),
  (1090, 209, 3, 'system:dict:type:list', '查看字典类型', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1091, 209, 3, 'system:dict:type:create', '创建字典类型', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1092, 209, 3, 'system:dict:type:update', '编辑字典类型', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1093, 209, 3, 'system:dict:type:status', '修改字典类型状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1098, 209, 3, 'system:dict:type:delete', '删除字典类型', '', '', '', 45, 1, '系统内置按钮', NOW(), NOW()),
  (1094, 209, 3, 'system:dict:item:list', '查看字典项', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (1095, 209, 3, 'system:dict:item:create', '创建字典项', '', '', '', 60, 1, '系统内置按钮', NOW(), NOW()),
  (1096, 209, 3, 'system:dict:item:update', '编辑字典项', '', '', '', 70, 1, '系统内置按钮', NOW(), NOW()),
  (1097, 209, 3, 'system:dict:item:status', '修改字典项状态', '', '', '', 80, 1, '系统内置按钮', NOW(), NOW()),
  (1099, 209, 3, 'system:dict:item:delete', '删除字典项', '', '', '', 90, 1, '系统内置按钮', NOW(), NOW()),
  (205, 101, 2, 'system:file', '文件管理', '/system/files', 'system/FileView', 'folder', 30, 1, '系统内置菜单', NOW(), NOW()),
  (1050, 205, 3, 'system:file:list', '查看文件', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1051, 205, 3, 'system:file:upload', '上传文件', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (210, 101, 2, 'system:attachment', '附件中心', '/system/attachments', 'system/AttachmentView', 'files', 40, 1, '系统内置菜单', NOW(), NOW()),
  (1100, 210, 3, 'system:attachment:list', '查看附件', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1101, 210, 3, 'system:attachment:upload', '上传附件', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1102, 210, 3, 'system:attachment:update', '编辑附件', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1103, 210, 3, 'system:attachment:status', '修改附件状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (208, 101, 2, 'system:notice', '公告管理', '/system/notices', 'system/NoticeView', 'notifications', 50, 1, '系统内置菜单', NOW(), NOW()),
  (1080, 208, 3, 'system:notice:list', '查看公告', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1081, 208, 3, 'system:notice:create', '创建公告', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1082, 208, 3, 'system:notice:update', '编辑公告', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1083, 208, 3, 'system:notice:status', '修改公告状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1084, 208, 3, 'system:notice:delete', '删除公告', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (213, 101, 2, 'system:message', '消息提醒', '/system/messages', 'system/MessageView', 'notifications', 60, 1, '系统内置菜单', NOW(), NOW()),
  (1130, 213, 3, 'system:message:template:list', '查看消息模板', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1131, 213, 3, 'system:message:template:create', '创建消息模板', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1132, 213, 3, 'system:message:template:update', '编辑消息模板', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1133, 213, 3, 'system:message:template:status', '修改消息模板状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1134, 213, 3, 'system:message:reminder:list', '查看提醒规则', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (1135, 213, 3, 'system:message:reminder:create', '创建提醒规则', '', '', '', 60, 1, '系统内置按钮', NOW(), NOW()),
  (1136, 213, 3, 'system:message:reminder:update', '编辑提醒规则', '', '', '', 70, 1, '系统内置按钮', NOW(), NOW()),
  (1137, 213, 3, 'system:message:reminder:status', '修改提醒规则状态', '', '', '', 80, 1, '系统内置按钮', NOW(), NOW()),
  (214, 101, 2, 'system:mail', '邮件管理', '/system/mails', 'system/MailView', 'mail', 70, 1, '系统内置菜单', NOW(), NOW()),
  (1140, 214, 3, 'system:mail:account:list', '查看邮箱账号', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1141, 214, 3, 'system:mail:account:create', '创建邮箱账号', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1142, 214, 3, 'system:mail:account:update', '编辑邮箱账号', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1143, 214, 3, 'system:mail:account:status', '修改邮箱账号状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1144, 214, 3, 'system:mail:account:delete', '删除邮箱账号', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (1145, 214, 3, 'system:mail:account:test', '测试邮箱账号', '', '', '', 60, 1, '系统内置按钮', NOW(), NOW()),
  (1146, 214, 3, 'system:mail:template:list', '查看邮件模板', '', '', '', 70, 1, '系统内置按钮', NOW(), NOW()),
  (1147, 214, 3, 'system:mail:template:create', '创建邮件模板', '', '', '', 80, 1, '系统内置按钮', NOW(), NOW()),
  (1148, 214, 3, 'system:mail:template:update', '编辑邮件模板', '', '', '', 90, 1, '系统内置按钮', NOW(), NOW()),
  (1149, 214, 3, 'system:mail:template:status', '修改邮件模板状态', '', '', '', 100, 1, '系统内置按钮', NOW(), NOW()),
  (1150, 214, 3, 'system:mail:template:delete', '删除邮件模板', '', '', '', 110, 1, '系统内置按钮', NOW(), NOW()),
  (1151, 214, 3, 'system:mail:template:render', '预览邮件模板', '', '', '', 120, 1, '系统内置按钮', NOW(), NOW()),
  (1152, 214, 3, 'system:mail:send', '发送邮件', '', '', '', 130, 1, '系统内置按钮', NOW(), NOW()),
  (1153, 214, 3, 'system:mail:log', '查看邮件日志', '', '', '', 140, 1, '系统内置按钮', NOW(), NOW()),
  (200, 102, 2, 'system:health', '系统状态', '/audit/health', 'system/HealthView', 'pulse', 10, 1, '系统内置菜单', NOW(), NOW()),
  (1001, 200, 3, 'system:health:view', '查看系统状态', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (206, 102, 2, 'system:operation-log', '操作日志', '/audit/operation-logs', 'system/OperationLogView', 'list', 20, 1, '系统内置菜单', NOW(), NOW()),
  (1060, 206, 3, 'system:operation-log:list', '查看操作日志', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (207, 102, 2, 'system:login-log', '登录日志', '/audit/login-logs', 'system/LoginLogView', 'time', 30, 1, '系统内置菜单', NOW(), NOW()),
  (1070, 207, 3, 'system:login-log:list', '查看登录日志', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW());

INSERT INTO sys_dict_type (id, code, name, sort, status, remark, created_at, updated_at)
VALUES
  (1, 'common:yes-no', '是否字典', 10, 1, '系统内置基础字典', NOW(), NOW()),
  (2, 'notice:level', '公告级别', 20, 1, '系统内置公告字典', NOW(), NOW());

INSERT INTO sys_dict_item (id, type_id, item_key, label, value, tag_type, sort, status, remark, created_at, updated_at)
VALUES
  (1, 1, 'yes', '是', '1', 'success', 10, 1, '系统内置基础字典项', NOW(), NOW()),
  (2, 1, 'no', '否', '0', 'default', 20, 1, '系统内置基础字典项', NOW(), NOW()),
  (3, 2, 'info', '普通公告', 'info', 'info', 10, 1, '系统内置公告字典项', NOW(), NOW()),
  (4, 2, 'warning', '重要公告', 'warning', 'warning', 20, 1, '系统内置公告字典项', NOW(), NOW());

INSERT INTO sys_message_template (id, code, name, title, content, type, variables, sort, status, is_system, remark, created_at, updated_at)
VALUES
  (1, 'auth:login-success', '登录成功提醒', '账号 {{username}} 登录成功', '账号 {{username}} 于 {{login_time}} 从 {{ip}} 登录系统。', 1, 'username=用户名; login_time=登录时间; ip=客户端 IP', 10, 1, TRUE, '系统内置登录提醒模板', NOW(), NOW()),
  (2, 'account:password-expire', '密码到期提醒', '密码即将到期', '你的账号密码将在 {{expire_days}} 天后到期，请及时修改密码。', 2, 'expire_days=剩余天数', 20, 1, TRUE, '系统内置账号安全提醒模板', NOW(), NOW());

INSERT INTO sys_message_reminder (id, code, name, trigger_event, template_id, channels, receiver_type, receiver_values, advance_minutes, link_url, sort, status, is_system, remark, created_at, updated_at)
VALUES
  (1, 'auth:login-success:super-admin', '登录成功通知超级管理员', 'auth:login:success', 1, 'notification', 1, 'super_admin', 0, '/audit/login-logs', 10, 1, TRUE, '系统内置登录安全提醒规则', NOW(), NOW()),
  (2, 'account:password-expire:self', '密码到期提醒本人', 'account:password:expire', 2, 'notification', 4, '', 4320, '/account/profile', 20, 1, TRUE, '系统内置账号安全提醒规则', NOW(), NOW());

INSERT INTO sys_api (id, code, name, module, method, path, sort, status, remark, created_at, updated_at)
VALUES
  (1, 'system:api:list', '查看接口权限元数据', 'iam', 'GET', '/api/v1/system/apis', 10, 1, '系统内置接口权限', NOW(), NOW()),
  (2, 'system:health:view', '查看系统状态', 'audit', 'GET', '/api/v1/system/health', 10, 1, '系统内置接口权限', NOW(), NOW()),
  (3, 'system:user:list', '查看用户', 'iam', 'GET', '/api/v1/system/users', 30, 1, '系统内置接口权限', NOW(), NOW()),
  (4, 'system:user:create', '创建用户', 'iam', 'POST', '/api/v1/system/users', 31, 1, '系统内置接口权限', NOW(), NOW()),
  (5, 'system:user:update', '编辑用户', 'iam', 'POST', '/api/v1/system/users/:id/update', 32, 1, '系统内置接口权限', NOW(), NOW()),
  (6, 'system:user:status', '修改用户状态', 'iam', 'POST', '/api/v1/system/users/:id/status', 33, 1, '系统内置接口权限', NOW(), NOW()),
  (7, 'system:user:assign-role', '分配用户角色', 'iam', 'POST', '/api/v1/system/users/:id/roles', 34, 1, '系统内置接口权限', NOW(), NOW()),
  (8, 'system:user:delete', '删除用户', 'iam', 'POST', '/api/v1/system/users/:id/delete', 35, 1, '系统内置接口权限', NOW(), NOW()),
  (9, 'system:role:list', '查看角色', 'iam', 'GET', '/api/v1/system/roles', 40, 1, '系统内置接口权限', NOW(), NOW()),
  (10, 'system:role:create', '创建角色', 'iam', 'POST', '/api/v1/system/roles', 41, 1, '系统内置接口权限', NOW(), NOW()),
  (11, 'system:role:update', '编辑角色', 'iam', 'POST', '/api/v1/system/roles/:id/update', 42, 1, '系统内置接口权限', NOW(), NOW()),
  (12, 'system:role:status', '修改角色状态', 'iam', 'POST', '/api/v1/system/roles/:id/status', 43, 1, '系统内置接口权限', NOW(), NOW()),
  (13, 'system:role:permission', '分配接口权限', 'iam', 'POST', '/api/v1/system/roles/:id/permissions', 44, 1, '系统内置接口权限', NOW(), NOW()),
  (14, 'system:role:menu', '分配菜单权限', 'iam', 'POST', '/api/v1/system/roles/:id/menus', 45, 1, '系统内置接口权限', NOW(), NOW()),
  (15, 'system:role:delete', '删除角色', 'iam', 'POST', '/api/v1/system/roles/:id/delete', 46, 1, '系统内置接口权限', NOW(), NOW()),
  (16, 'system:menu:list', '查看菜单', 'iam', 'GET', '/api/v1/system/menus', 50, 1, '系统内置接口权限', NOW(), NOW()),
  (17, 'system:menu:create', '创建菜单', 'iam', 'POST', '/api/v1/system/menus', 51, 1, '系统内置接口权限', NOW(), NOW()),
  (18, 'system:menu:update', '编辑菜单', 'iam', 'POST', '/api/v1/system/menus/:id/update', 52, 1, '系统内置接口权限', NOW(), NOW()),
  (19, 'system:menu:status', '修改菜单状态', 'iam', 'POST', '/api/v1/system/menus/:id/status', 53, 1, '系统内置接口权限', NOW(), NOW()),
  (20, 'system:menu:delete', '删除菜单', 'iam', 'POST', '/api/v1/system/menus/:id/delete', 54, 1, '系统内置接口权限', NOW(), NOW()),
  (21, 'system:department:list', '查看部门', 'iam', 'GET', '/api/v1/system/departments', 60, 1, '系统内置接口权限', NOW(), NOW()),
  (22, 'system:department:create', '创建部门', 'iam', 'POST', '/api/v1/system/departments', 61, 1, '系统内置接口权限', NOW(), NOW()),
  (23, 'system:department:update', '编辑部门', 'iam', 'POST', '/api/v1/system/departments/:id/update', 62, 1, '系统内置接口权限', NOW(), NOW()),
  (24, 'system:department:status', '修改部门状态', 'iam', 'POST', '/api/v1/system/departments/:id/status', 63, 1, '系统内置接口权限', NOW(), NOW()),
  (25, 'system:department:delete', '删除部门', 'iam', 'POST', '/api/v1/system/departments/:id/delete', 64, 1, '系统内置接口权限', NOW(), NOW()),
  (26, 'system:post:list', '查看岗位', 'iam', 'GET', '/api/v1/system/posts', 70, 1, '系统内置接口权限', NOW(), NOW()),
  (27, 'system:post:create', '创建岗位', 'iam', 'POST', '/api/v1/system/posts', 71, 1, '系统内置接口权限', NOW(), NOW()),
  (28, 'system:post:update', '编辑岗位', 'iam', 'POST', '/api/v1/system/posts/:id/update', 72, 1, '系统内置接口权限', NOW(), NOW()),
  (29, 'system:post:status', '修改岗位状态', 'iam', 'POST', '/api/v1/system/posts/:id/status', 73, 1, '系统内置接口权限', NOW(), NOW()),
  (30, 'system:post:delete', '删除岗位', 'iam', 'POST', '/api/v1/system/posts/:id/delete', 74, 1, '系统内置接口权限', NOW(), NOW()),
  (31, 'system:config:list', '查看配置', 'system', 'GET', '/api/v1/system/configs', 10, 1, '系统内置接口权限', NOW(), NOW()),
  (32, 'system:config:create', '创建配置', 'system', 'POST', '/api/v1/system/configs', 11, 1, '系统内置接口权限', NOW(), NOW()),
  (33, 'system:config:update', '编辑配置', 'system', 'POST', '/api/v1/system/configs/:id/update', 12, 1, '系统内置接口权限', NOW(), NOW()),
  (34, 'system:config:status', '修改配置状态', 'system', 'POST', '/api/v1/system/configs/:id/status', 13, 1, '系统内置接口权限', NOW(), NOW()),
  (35, 'system:config:delete', '删除配置', 'system', 'POST', '/api/v1/system/configs/:id/delete', 14, 1, '系统内置接口权限', NOW(), NOW()),
  (36, 'system:config:value', '读取配置值', 'system', 'GET', '/api/v1/system/configs/value/:key', 15, 1, '系统内置接口权限', NOW(), NOW()),
  (37, 'system:dict:type:list', '查看字典类型', 'system', 'GET', '/api/v1/system/dict-types', 20, 1, '系统内置接口权限', NOW(), NOW()),
  (38, 'system:dict:type:create', '创建字典类型', 'system', 'POST', '/api/v1/system/dict-types', 21, 1, '系统内置接口权限', NOW(), NOW()),
  (39, 'system:dict:type:update', '编辑字典类型', 'system', 'POST', '/api/v1/system/dict-types/:id/update', 22, 1, '系统内置接口权限', NOW(), NOW()),
  (40, 'system:dict:type:status', '修改字典类型状态', 'system', 'POST', '/api/v1/system/dict-types/:id/status', 23, 1, '系统内置接口权限', NOW(), NOW()),
  (41, 'system:dict:type:delete', '删除字典类型', 'system', 'POST', '/api/v1/system/dict-types/:id/delete', 24, 1, '系统内置接口权限', NOW(), NOW()),
  (42, 'system:dict:item:list', '查看字典项', 'system', 'GET', '/api/v1/system/dict-items', 25, 1, '系统内置接口权限', NOW(), NOW()),
  (43, 'system:dict:item:create', '创建字典项', 'system', 'POST', '/api/v1/system/dict-items', 26, 1, '系统内置接口权限', NOW(), NOW()),
  (44, 'system:dict:item:update', '编辑字典项', 'system', 'POST', '/api/v1/system/dict-items/:id/update', 27, 1, '系统内置接口权限', NOW(), NOW()),
  (45, 'system:dict:item:status', '修改字典项状态', 'system', 'POST', '/api/v1/system/dict-items/:id/status', 28, 1, '系统内置接口权限', NOW(), NOW()),
  (46, 'system:dict:item:delete', '删除字典项', 'system', 'POST', '/api/v1/system/dict-items/:id/delete', 29, 1, '系统内置接口权限', NOW(), NOW()),
  (47, 'system:file:list', '查看文件', 'system', 'GET', '/api/v1/system/files', 30, 1, '系统内置接口权限', NOW(), NOW()),
  (48, 'system:file:upload', '上传文件', 'system', 'POST', '/api/v1/system/files', 31, 1, '系统内置接口权限', NOW(), NOW()),
  (49, 'system:attachment:list', '查看附件', 'system', 'GET', '/api/v1/system/attachments', 40, 1, '系统内置接口权限', NOW(), NOW()),
  (50, 'system:attachment:upload', '上传附件', 'system', 'POST', '/api/v1/system/attachments', 41, 1, '系统内置接口权限', NOW(), NOW()),
  (51, 'system:attachment:update', '编辑附件', 'system', 'POST', '/api/v1/system/attachments/:id/update', 42, 1, '系统内置接口权限', NOW(), NOW()),
  (52, 'system:attachment:status', '修改附件状态', 'system', 'POST', '/api/v1/system/attachments/:id/status', 43, 1, '系统内置接口权限', NOW(), NOW()),
  (53, 'system:notice:list', '查看公告', 'system', 'GET', '/api/v1/system/notices', 50, 1, '系统内置接口权限', NOW(), NOW()),
  (54, 'system:notice:create', '创建公告', 'system', 'POST', '/api/v1/system/notices', 51, 1, '系统内置接口权限', NOW(), NOW()),
  (55, 'system:notice:update', '编辑公告', 'system', 'POST', '/api/v1/system/notices/:id/update', 52, 1, '系统内置接口权限', NOW(), NOW()),
  (56, 'system:notice:status', '修改公告状态', 'system', 'POST', '/api/v1/system/notices/:id/status', 53, 1, '系统内置接口权限', NOW(), NOW()),
  (57, 'system:notice:delete', '删除公告', 'system', 'POST', '/api/v1/system/notices/:id/delete', 54, 1, '系统内置接口权限', NOW(), NOW()),
  (58, 'system:operation-log:list', '查看操作日志', 'audit', 'GET', '/api/v1/system/operation-logs', 20, 1, '系统内置接口权限', NOW(), NOW()),
  (59, 'system:login-log:list', '查看登录日志', 'audit', 'GET', '/api/v1/system/login-logs', 30, 1, '系统内置接口权限', NOW(), NOW()),
  (60, 'system:notification:list', '查看通知', 'system', 'GET', '/api/v1/system/notifications', 60, 1, '系统内置接口权限', NOW(), NOW()),
  (61, 'system:notification:unread-count', '查看未读通知数', 'system', 'GET', '/api/v1/system/notifications/unread-count', 61, 1, '系统内置接口权限', NOW(), NOW()),
  (62, 'system:notification:mark-read', '标记通知已读', 'system', 'POST', '/api/v1/system/notifications/mark-read', 62, 1, '系统内置接口权限', NOW(), NOW()),
  (63, 'system:notification:mark-all-read', '全部通知已读', 'system', 'POST', '/api/v1/system/notifications/mark-all-read', 63, 1, '系统内置接口权限', NOW(), NOW()),
  (64, 'system:message:template:list', '查看消息模板', 'system', 'GET', '/api/v1/system/message-templates', 70, 1, '系统内置接口权限', NOW(), NOW()),
  (65, 'system:message:template:create', '创建消息模板', 'system', 'POST', '/api/v1/system/message-templates', 71, 1, '系统内置接口权限', NOW(), NOW()),
  (66, 'system:message:template:update', '编辑消息模板', 'system', 'POST', '/api/v1/system/message-templates/:id/update', 72, 1, '系统内置接口权限', NOW(), NOW()),
  (67, 'system:message:template:status', '修改消息模板状态', 'system', 'POST', '/api/v1/system/message-templates/:id/status', 73, 1, '系统内置接口权限', NOW(), NOW()),
  (68, 'system:message:reminder:list', '查看提醒规则', 'system', 'GET', '/api/v1/system/message-reminders', 74, 1, '系统内置接口权限', NOW(), NOW()),
  (69, 'system:message:reminder:create', '创建提醒规则', 'system', 'POST', '/api/v1/system/message-reminders', 75, 1, '系统内置接口权限', NOW(), NOW()),
  (70, 'system:message:reminder:update', '编辑提醒规则', 'system', 'POST', '/api/v1/system/message-reminders/:id/update', 76, 1, '系统内置接口权限', NOW(), NOW()),
  (71, 'system:message:reminder:status', '修改提醒规则状态', 'system', 'POST', '/api/v1/system/message-reminders/:id/status', 77, 1, '系统内置接口权限', NOW(), NOW()),
  (72, 'system:mail:account:list', '查看邮箱账号', 'system', 'GET', '/api/v1/system/mail/accounts', 80, 1, '系统内置接口权限', NOW(), NOW()),
  (73, 'system:mail:account:create', '创建邮箱账号', 'system', 'POST', '/api/v1/system/mail/accounts', 81, 1, '系统内置接口权限', NOW(), NOW()),
  (74, 'system:mail:account:update', '编辑邮箱账号', 'system', 'POST', '/api/v1/system/mail/accounts/:id/update', 82, 1, '系统内置接口权限', NOW(), NOW()),
  (75, 'system:mail:account:status', '修改邮箱账号状态', 'system', 'POST', '/api/v1/system/mail/accounts/:id/status', 83, 1, '系统内置接口权限', NOW(), NOW()),
  (76, 'system:mail:account:delete', '删除邮箱账号', 'system', 'POST', '/api/v1/system/mail/accounts/:id/delete', 84, 1, '系统内置接口权限', NOW(), NOW()),
  (77, 'system:mail:account:test', '测试邮箱账号', 'system', 'POST', '/api/v1/system/mail/accounts/:id/test', 85, 1, '系统内置接口权限', NOW(), NOW()),
  (78, 'system:mail:template:list', '查看邮件模板', 'system', 'GET', '/api/v1/system/mail/templates', 86, 1, '系统内置接口权限', NOW(), NOW()),
  (79, 'system:mail:template:create', '创建邮件模板', 'system', 'POST', '/api/v1/system/mail/templates', 87, 1, '系统内置接口权限', NOW(), NOW()),
  (80, 'system:mail:template:update', '编辑邮件模板', 'system', 'POST', '/api/v1/system/mail/templates/:id/update', 88, 1, '系统内置接口权限', NOW(), NOW()),
  (81, 'system:mail:template:status', '修改邮件模板状态', 'system', 'POST', '/api/v1/system/mail/templates/:id/status', 89, 1, '系统内置接口权限', NOW(), NOW()),
  (82, 'system:mail:template:delete', '删除邮件模板', 'system', 'POST', '/api/v1/system/mail/templates/:id/delete', 90, 1, '系统内置接口权限', NOW(), NOW()),
  (83, 'system:mail:template:render', '预览邮件模板', 'system', 'POST', '/api/v1/system/mail/templates/:id/render', 91, 1, '系统内置接口权限', NOW(), NOW()),
  (84, 'system:mail:send', '发送邮件', 'system', 'POST', '/api/v1/system/mail/send', 92, 1, '系统内置接口权限', NOW(), NOW()),
  (85, 'system:mail:log', '查看邮件日志', 'system', 'GET', '/api/v1/system/mail/logs', 93, 1, '系统内置接口权限', NOW(), NOW());

INSERT INTO sys_role_api (role_id, api_id, created_at, updated_at)
SELECT 1, id, NOW(), NOW()
FROM sys_api
WHERE status = 1
ORDER BY id;

INSERT INTO casbin_rule (ptype, v0, v1, v2)
SELECT 'p', 'super_admin', path, method
FROM sys_api
WHERE status = 1
ORDER BY id;

INSERT INTO sys_role_menu (role_id, menu_id, created_at, updated_at)
VALUES
  (1, 100, NOW(), NOW()),
  (1, 101, NOW(), NOW()),
  (1, 102, NOW(), NOW()),
  (1, 211, NOW(), NOW()),
  (1, 1110, NOW(), NOW()),
  (1, 1111, NOW(), NOW()),
  (1, 1112, NOW(), NOW()),
  (1, 1113, NOW(), NOW()),
  (1, 1114, NOW(), NOW()),
  (1, 212, NOW(), NOW()),
  (1, 1120, NOW(), NOW()),
  (1, 1121, NOW(), NOW()),
  (1, 1122, NOW(), NOW()),
  (1, 1123, NOW(), NOW()),
  (1, 1124, NOW(), NOW()),
  (1, 201, NOW(), NOW()),
  (1, 1010, NOW(), NOW()),
  (1, 1011, NOW(), NOW()),
  (1, 1012, NOW(), NOW()),
  (1, 1013, NOW(), NOW()),
  (1, 1014, NOW(), NOW()),
  (1, 1015, NOW(), NOW()),
  (1, 202, NOW(), NOW()),
  (1, 1020, NOW(), NOW()),
  (1, 1021, NOW(), NOW()),
  (1, 1022, NOW(), NOW()),
  (1, 1023, NOW(), NOW()),
  (1, 1024, NOW(), NOW()),
  (1, 1025, NOW(), NOW()),
  (1, 1026, NOW(), NOW()),
  (1, 203, NOW(), NOW()),
  (1, 1030, NOW(), NOW()),
  (1, 1031, NOW(), NOW()),
  (1, 1032, NOW(), NOW()),
  (1, 1033, NOW(), NOW()),
  (1, 1034, NOW(), NOW()),
  (1, 204, NOW(), NOW()),
  (1, 1040, NOW(), NOW()),
  (1, 1041, NOW(), NOW()),
  (1, 1042, NOW(), NOW()),
  (1, 1043, NOW(), NOW()),
  (1, 1044, NOW(), NOW()),
  (1, 1045, NOW(), NOW()),
  (1, 209, NOW(), NOW()),
  (1, 1090, NOW(), NOW()),
  (1, 1091, NOW(), NOW()),
  (1, 1092, NOW(), NOW()),
  (1, 1093, NOW(), NOW()),
  (1, 1098, NOW(), NOW()),
  (1, 1094, NOW(), NOW()),
  (1, 1095, NOW(), NOW()),
  (1, 1096, NOW(), NOW()),
  (1, 1097, NOW(), NOW()),
  (1, 1099, NOW(), NOW()),
  (1, 205, NOW(), NOW()),
  (1, 1050, NOW(), NOW()),
  (1, 1051, NOW(), NOW()),
  (1, 210, NOW(), NOW()),
  (1, 1100, NOW(), NOW()),
  (1, 1101, NOW(), NOW()),
  (1, 1102, NOW(), NOW()),
  (1, 1103, NOW(), NOW()),
  (1, 208, NOW(), NOW()),
  (1, 1080, NOW(), NOW()),
  (1, 1081, NOW(), NOW()),
  (1, 1082, NOW(), NOW()),
  (1, 1083, NOW(), NOW()),
  (1, 1084, NOW(), NOW()),
  (1, 213, NOW(), NOW()),
  (1, 1130, NOW(), NOW()),
  (1, 1131, NOW(), NOW()),
  (1, 1132, NOW(), NOW()),
  (1, 1133, NOW(), NOW()),
  (1, 1134, NOW(), NOW()),
  (1, 1135, NOW(), NOW()),
  (1, 1136, NOW(), NOW()),
  (1, 1137, NOW(), NOW()),
  (1, 214, NOW(), NOW()),
  (1, 1140, NOW(), NOW()),
  (1, 1141, NOW(), NOW()),
  (1, 1142, NOW(), NOW()),
  (1, 1143, NOW(), NOW()),
  (1, 1144, NOW(), NOW()),
  (1, 1145, NOW(), NOW()),
  (1, 1146, NOW(), NOW()),
  (1, 1147, NOW(), NOW()),
  (1, 1148, NOW(), NOW()),
  (1, 1149, NOW(), NOW()),
  (1, 1150, NOW(), NOW()),
  (1, 1151, NOW(), NOW()),
  (1, 1152, NOW(), NOW()),
  (1, 1153, NOW(), NOW()),
  (1, 200, NOW(), NOW()),
  (1, 1001, NOW(), NOW()),
  (1, 206, NOW(), NOW()),
  (1, 1060, NOW(), NOW()),
  (1, 207, NOW(), NOW()),
  (1, 1070, NOW(), NOW());

SELECT setval(pg_get_serial_sequence('sys_role', 'id'), COALESCE((SELECT MAX(id) FROM sys_role), 1), true);
SELECT setval(pg_get_serial_sequence('sys_config', 'id'), COALESCE((SELECT MAX(id) FROM sys_config), 1), true);
SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), COALESCE((SELECT MAX(id) FROM sys_menu), 1), true);
SELECT setval(pg_get_serial_sequence('sys_api', 'id'), COALESCE((SELECT MAX(id) FROM sys_api), 1), true);
SELECT setval(pg_get_serial_sequence('sys_dict_type', 'id'), COALESCE((SELECT MAX(id) FROM sys_dict_type), 1), true);
SELECT setval(pg_get_serial_sequence('sys_dict_item', 'id'), COALESCE((SELECT MAX(id) FROM sys_dict_item), 1), true);
SELECT setval(pg_get_serial_sequence('sys_message_template', 'id'), COALESCE((SELECT MAX(id) FROM sys_message_template), 1), true);
SELECT setval(pg_get_serial_sequence('sys_message_reminder', 'id'), COALESCE((SELECT MAX(id) FROM sys_message_reminder), 1), true);
SELECT setval(pg_get_serial_sequence('sys_mail_account', 'id'), COALESCE((SELECT MAX(id) FROM sys_mail_account), 1), true);
SELECT setval(pg_get_serial_sequence('sys_mail_template', 'id'), COALESCE((SELECT MAX(id) FROM sys_mail_template), 1), true);
SELECT setval(pg_get_serial_sequence('sys_mail_log', 'id'), COALESCE((SELECT MAX(id) FROM sys_mail_log), 1), true);

-- ============================================================================
-- Migration baseline
-- ============================================================================

CREATE TABLE IF NOT EXISTS schema_migrations (version BIGINT NOT NULL PRIMARY KEY, dirty BOOLEAN NOT NULL);
INSERT INTO schema_migrations (version, dirty) VALUES (1, false)
ON CONFLICT (version) DO UPDATE SET dirty = EXCLUDED.dirty;
