-- Stable full initialization SQL for postgres.
-- Generated by scripts/build-full-migrations.sh.
--
-- Covers final schema + built-in seed data.
-- Does NOT create the first admin user.
-- Create the first admin with POST /api/v1/setup/init after import.

-- ============================================================================
-- Final schema
-- ============================================================================

-- 系统用户表
CREATE TABLE sys_user (
  id BIGSERIAL PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  nickname VARCHAR(64) NOT NULL DEFAULT '',
  department_id BIGINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_user_username ON sys_user (username);
CREATE INDEX idx_sys_user_department_id ON sys_user (department_id);
CREATE INDEX idx_sys_user_deleted_at ON sys_user (deleted_at);

COMMENT ON TABLE sys_user IS '后台用户表';
COMMENT ON COLUMN sys_user.id IS '用户记录主键，数据库自增生成';
COMMENT ON COLUMN sys_user.username IS '登录用户名';
COMMENT ON COLUMN sys_user.password_hash IS '密码哈希';
COMMENT ON COLUMN sys_user.nickname IS '管理台展示名称';
COMMENT ON COLUMN sys_user.department_id IS '部门 ID，对应 sys_department.id';
COMMENT ON COLUMN sys_user.status IS '用户状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_user.created_at IS '创建时间';
COMMENT ON COLUMN sys_user.updated_at IS '更新时间';
COMMENT ON COLUMN sys_user.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 系统角色表
CREATE TABLE sys_role (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  data_scope VARCHAR(32) NOT NULL DEFAULT 'self',
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_role_code ON sys_role (code);
CREATE INDEX idx_sys_role_status ON sys_role (status);
CREATE INDEX idx_sys_role_deleted_at ON sys_role (deleted_at);

COMMENT ON TABLE sys_role IS '后台角色表';
COMMENT ON COLUMN sys_role.id IS '角色记录主键，数据库自增生成';
COMMENT ON COLUMN sys_role.code IS '角色编码';
COMMENT ON COLUMN sys_role.name IS '角色名称';
COMMENT ON COLUMN sys_role.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_role.data_scope IS '数据权限范围：all/dept/dept_and_children/self/custom_dept';
COMMENT ON COLUMN sys_role.status IS '角色状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_role.remark IS '备注';
COMMENT ON COLUMN sys_role.created_at IS '创建时间';
COMMENT ON COLUMN sys_role.updated_at IS '更新时间';
COMMENT ON COLUMN sys_role.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 用户角色关系表
CREATE TABLE sys_user_role (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  role_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_sys_user_role_user_role ON sys_user_role (user_id, role_id);
CREATE INDEX idx_sys_user_role_user_id ON sys_user_role (user_id);
CREATE INDEX idx_sys_user_role_role_id ON sys_user_role (role_id);

COMMENT ON TABLE sys_user_role IS '用户角色关系表';
COMMENT ON COLUMN sys_user_role.id IS '关系记录主键，数据库自增生成';
COMMENT ON COLUMN sys_user_role.user_id IS '用户 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_user_role.role_id IS '角色 ID，对应 sys_role.id';
COMMENT ON COLUMN sys_user_role.created_at IS '绑定时间';
COMMENT ON COLUMN sys_user_role.updated_at IS '更新时间';

-- 系统菜单和按钮表
CREATE TABLE sys_menu (
  id BIGSERIAL PRIMARY KEY,
  parent_id BIGINT NOT NULL DEFAULT 0,
  type SMALLINT NOT NULL,
  code VARCHAR(128) NOT NULL,
  title VARCHAR(64) NOT NULL,
  path VARCHAR(255) NOT NULL DEFAULT '',
  component VARCHAR(255) NOT NULL DEFAULT '',
  icon VARCHAR(64) NOT NULL DEFAULT '',
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_menu_code ON sys_menu (code);
CREATE INDEX idx_sys_menu_parent_id ON sys_menu (parent_id);
CREATE INDEX idx_sys_menu_type ON sys_menu (type);
CREATE INDEX idx_sys_menu_status ON sys_menu (status);
CREATE INDEX idx_sys_menu_deleted_at ON sys_menu (deleted_at);

COMMENT ON TABLE sys_menu IS '后台菜单和按钮表';
COMMENT ON COLUMN sys_menu.id IS '菜单记录主键，数据库自增生成';
COMMENT ON COLUMN sys_menu.parent_id IS '父级菜单 ID，根节点为 0';
COMMENT ON COLUMN sys_menu.type IS '节点类型：1 目录，2 菜单，3 按钮';
COMMENT ON COLUMN sys_menu.code IS '菜单或按钮编码，系统内唯一';
COMMENT ON COLUMN sys_menu.title IS '展示名称';
COMMENT ON COLUMN sys_menu.path IS '前端路由路径';
COMMENT ON COLUMN sys_menu.component IS '前端组件路径';
COMMENT ON COLUMN sys_menu.icon IS '图标标识';
COMMENT ON COLUMN sys_menu.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_menu.status IS '菜单状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_menu.remark IS '备注';
COMMENT ON COLUMN sys_menu.created_at IS '创建时间';
COMMENT ON COLUMN sys_menu.updated_at IS '更新时间';
COMMENT ON COLUMN sys_menu.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 角色菜单关系表
CREATE TABLE sys_role_menu (
  id BIGSERIAL PRIMARY KEY,
  role_id BIGINT NOT NULL,
  menu_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_sys_role_menu_role_menu ON sys_role_menu (role_id, menu_id);
CREATE INDEX idx_sys_role_menu_role_id ON sys_role_menu (role_id);
CREATE INDEX idx_sys_role_menu_menu_id ON sys_role_menu (menu_id);

COMMENT ON TABLE sys_role_menu IS '角色菜单关系表';
COMMENT ON COLUMN sys_role_menu.id IS '关系记录主键，数据库自增生成';
COMMENT ON COLUMN sys_role_menu.role_id IS '角色 ID，对应 sys_role.id';
COMMENT ON COLUMN sys_role_menu.menu_id IS '菜单 ID，对应 sys_menu.id';
COMMENT ON COLUMN sys_role_menu.created_at IS '绑定时间';
COMMENT ON COLUMN sys_role_menu.updated_at IS '更新时间';

-- 系统配置表
CREATE TABLE sys_config (
  id BIGSERIAL PRIMARY KEY,
  group_code VARCHAR(64) NOT NULL,
  config_key VARCHAR(128) NOT NULL,
  name VARCHAR(64) NOT NULL,
  value TEXT NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_config_key ON sys_config (config_key);
CREATE INDEX idx_sys_config_group_code ON sys_config (group_code);
CREATE INDEX idx_sys_config_status ON sys_config (status);
CREATE INDEX idx_sys_config_deleted_at ON sys_config (deleted_at);

COMMENT ON TABLE sys_config IS '系统配置表';
COMMENT ON COLUMN sys_config.id IS '配置记录主键，数据库自增生成';
COMMENT ON COLUMN sys_config.group_code IS '配置分组，例如 site、upload';
COMMENT ON COLUMN sys_config.config_key IS '配置键，系统内唯一，例如 site:title';
COMMENT ON COLUMN sys_config.name IS '配置名称';
COMMENT ON COLUMN sys_config.value IS '配置值，统一按字符串存储';
COMMENT ON COLUMN sys_config.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_config.status IS '配置状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_config.remark IS '备注';
COMMENT ON COLUMN sys_config.created_at IS '创建时间';
COMMENT ON COLUMN sys_config.updated_at IS '更新时间';
COMMENT ON COLUMN sys_config.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 文件上传记录表
CREATE TABLE sys_file (
  id BIGSERIAL PRIMARY KEY,
  storage VARCHAR(32) NOT NULL DEFAULT 'local',
  original_name VARCHAR(255) NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  ext VARCHAR(32) NOT NULL DEFAULT '',
  mime_type VARCHAR(128) NOT NULL DEFAULT '',
  size BIGINT NOT NULL DEFAULT 0,
  sha256 VARCHAR(64) NOT NULL DEFAULT '',
  path VARCHAR(500) NOT NULL,
  url VARCHAR(500) NOT NULL,
  uploader_id BIGINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_sys_file_ext ON sys_file (ext);
CREATE INDEX idx_sys_file_sha256 ON sys_file (sha256);
CREATE INDEX idx_sys_file_uploader_id ON sys_file (uploader_id);
CREATE INDEX idx_sys_file_status ON sys_file (status);
CREATE INDEX idx_sys_file_deleted_at ON sys_file (deleted_at);

COMMENT ON TABLE sys_file IS '文件上传记录表';
COMMENT ON COLUMN sys_file.id IS '文件记录主键，数据库自增生成';
COMMENT ON COLUMN sys_file.storage IS '存储类型，本节使用 local';
COMMENT ON COLUMN sys_file.original_name IS '用户上传时的原始文件名';
COMMENT ON COLUMN sys_file.file_name IS '后端生成的保存文件名';
COMMENT ON COLUMN sys_file.ext IS '文件后缀，例如 .png、.pdf';
COMMENT ON COLUMN sys_file.mime_type IS '上传请求中的文件 MIME 类型';
COMMENT ON COLUMN sys_file.size IS '文件大小，单位字节';
COMMENT ON COLUMN sys_file.sha256 IS '文件内容 SHA-256 哈希';
COMMENT ON COLUMN sys_file.path IS '服务端保存路径';
COMMENT ON COLUMN sys_file.url IS '前端可访问地址';
COMMENT ON COLUMN sys_file.uploader_id IS '上传用户 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_file.status IS '文件状态：1 启用，2 停用';
COMMENT ON COLUMN sys_file.remark IS '备注';
COMMENT ON COLUMN sys_file.created_at IS '创建时间';
COMMENT ON COLUMN sys_file.updated_at IS '更新时间';
COMMENT ON COLUMN sys_file.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- 操作日志表
CREATE TABLE sys_operation_log (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL DEFAULT 0,
  username VARCHAR(64) NOT NULL DEFAULT '',
  method VARCHAR(10) NOT NULL,
  path VARCHAR(255) NOT NULL,
  route_path VARCHAR(255) NOT NULL DEFAULT '',
  query VARCHAR(1000) NOT NULL DEFAULT '',
  ip VARCHAR(64) NOT NULL DEFAULT '',
  user_agent VARCHAR(500) NOT NULL DEFAULT '',
  status_code INTEGER NOT NULL DEFAULT 0,
  latency_ms BIGINT NOT NULL DEFAULT 0,
  success BOOLEAN NOT NULL DEFAULT TRUE,
  error_message VARCHAR(500) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_sys_operation_log_user_id ON sys_operation_log (user_id);
CREATE INDEX idx_sys_operation_log_username ON sys_operation_log (username);
CREATE INDEX idx_sys_operation_log_method ON sys_operation_log (method);
CREATE INDEX idx_sys_operation_log_path ON sys_operation_log (path);
CREATE INDEX idx_sys_operation_log_route_path ON sys_operation_log (route_path);
CREATE INDEX idx_sys_operation_log_status_code ON sys_operation_log (status_code);
CREATE INDEX idx_sys_operation_log_success ON sys_operation_log (success);
CREATE INDEX idx_sys_operation_log_created_at ON sys_operation_log (created_at);

COMMENT ON TABLE sys_operation_log IS '操作日志表';
COMMENT ON COLUMN sys_operation_log.id IS '操作日志主键，数据库自增生成';
COMMENT ON COLUMN sys_operation_log.user_id IS '操作人 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_operation_log.username IS '操作人用户名';
COMMENT ON COLUMN sys_operation_log.method IS 'HTTP 请求方法';
COMMENT ON COLUMN sys_operation_log.path IS '实际请求路径';
COMMENT ON COLUMN sys_operation_log.route_path IS 'Gin 路由模板';
COMMENT ON COLUMN sys_operation_log.query IS '查询参数';
COMMENT ON COLUMN sys_operation_log.ip IS '客户端 IP';
COMMENT ON COLUMN sys_operation_log.user_agent IS '浏览器或客户端标识';
COMMENT ON COLUMN sys_operation_log.status_code IS 'HTTP 状态码';
COMMENT ON COLUMN sys_operation_log.latency_ms IS '请求耗时，单位毫秒';
COMMENT ON COLUMN sys_operation_log.success IS '是否成功';
COMMENT ON COLUMN sys_operation_log.error_message IS '错误摘要';
COMMENT ON COLUMN sys_operation_log.created_at IS '创建时间';

-- 登录日志表
CREATE TABLE sys_login_log (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL DEFAULT 0,
  username VARCHAR(64) NOT NULL DEFAULT '',
  status SMALLINT NOT NULL,
  message VARCHAR(255) NOT NULL DEFAULT '',
  ip VARCHAR(64) NOT NULL DEFAULT '',
  user_agent VARCHAR(500) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL
);

CREATE INDEX idx_sys_login_log_user_id ON sys_login_log (user_id);
CREATE INDEX idx_sys_login_log_username ON sys_login_log (username);
CREATE INDEX idx_sys_login_log_status ON sys_login_log (status);
CREATE INDEX idx_sys_login_log_ip ON sys_login_log (ip);
CREATE INDEX idx_sys_login_log_created_at ON sys_login_log (created_at);

COMMENT ON TABLE sys_login_log IS '登录日志表';
COMMENT ON COLUMN sys_login_log.id IS '登录日志主键，数据库自增生成';
COMMENT ON COLUMN sys_login_log.user_id IS '用户 ID，对应 sys_user.id；用户名不存在时为 0';
COMMENT ON COLUMN sys_login_log.username IS '登录用户名';
COMMENT ON COLUMN sys_login_log.status IS '登录状态：1 成功，2 失败';
COMMENT ON COLUMN sys_login_log.message IS '登录结果说明';
COMMENT ON COLUMN sys_login_log.ip IS '客户端 IP';
COMMENT ON COLUMN sys_login_log.user_agent IS '浏览器或客户端标识';
COMMENT ON COLUMN sys_login_log.created_at IS '创建时间';

-- 公告表
CREATE TABLE sys_notice (
  id BIGSERIAL PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  content TEXT NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE INDEX idx_sys_notice_deleted_at ON sys_notice (deleted_at);

COMMENT ON TABLE sys_notice IS '公告表';
COMMENT ON COLUMN sys_notice.id IS '公告记录主键，数据库自增生成';
COMMENT ON COLUMN sys_notice.title IS '公告标题';
COMMENT ON COLUMN sys_notice.content IS '公告内容';
COMMENT ON COLUMN sys_notice.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_notice.status IS '公告状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_notice.remark IS '备注';
COMMENT ON COLUMN sys_notice.created_at IS '创建时间';
COMMENT ON COLUMN sys_notice.updated_at IS '更新时间';
COMMENT ON COLUMN sys_notice.deleted_at IS '逻辑删除时间，NULL 表示未删除';

-- Casbin 权限策略表
CREATE TABLE casbin_rule (
  id BIGSERIAL PRIMARY KEY,
  ptype VARCHAR(100) NOT NULL DEFAULT '',
  v0 VARCHAR(100) NOT NULL DEFAULT '',
  v1 VARCHAR(100) NOT NULL DEFAULT '',
  v2 VARCHAR(100) NOT NULL DEFAULT '',
  v3 VARCHAR(100) NOT NULL DEFAULT '',
  v4 VARCHAR(100) NOT NULL DEFAULT '',
  v5 VARCHAR(100) NOT NULL DEFAULT ''
);

CREATE UNIQUE INDEX uk_casbin_rule_policy ON casbin_rule (ptype, v0, v1, v2, v3, v4, v5);
CREATE INDEX idx_casbin_rule_ptype ON casbin_rule (ptype);
CREATE INDEX idx_casbin_rule_subject ON casbin_rule (v0);

COMMENT ON TABLE casbin_rule IS 'Casbin 权限策略表';
COMMENT ON COLUMN casbin_rule.id IS '策略记录主键，数据库自增生成';
COMMENT ON COLUMN casbin_rule.ptype IS '策略类型，例如 p';
COMMENT ON COLUMN casbin_rule.v0 IS '策略主体，本项目存角色编码';
COMMENT ON COLUMN casbin_rule.v1 IS '资源路径';
COMMENT ON COLUMN casbin_rule.v2 IS '请求方法';
COMMENT ON COLUMN casbin_rule.v3 IS '预留字段';
COMMENT ON COLUMN casbin_rule.v4 IS '预留字段';
COMMENT ON COLUMN casbin_rule.v5 IS '预留字段';

CREATE TABLE sys_department (
  id BIGSERIAL PRIMARY KEY,
  parent_id BIGINT NOT NULL DEFAULT 0,
  ancestors VARCHAR(500) NOT NULL DEFAULT '',
  name VARCHAR(64) NOT NULL,
  code VARCHAR(64) NOT NULL,
  leader_user_id BIGINT NOT NULL DEFAULT 0,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_department_code
ON sys_department (code);

CREATE INDEX idx_sys_department_parent_id
ON sys_department (parent_id);

CREATE INDEX idx_sys_department_leader_user_id
ON sys_department (leader_user_id);

CREATE INDEX idx_sys_department_status
ON sys_department (status);

CREATE INDEX idx_sys_department_deleted_at
ON sys_department (deleted_at);

COMMENT ON TABLE sys_department IS '组织部门表';
COMMENT ON COLUMN sys_department.parent_id IS '父部门 ID，根节点为 0';
COMMENT ON COLUMN sys_department.ancestors IS '祖先路径，例如 0,1,3';
COMMENT ON COLUMN sys_department.name IS '部门名称';
COMMENT ON COLUMN sys_department.code IS '部门编码';
COMMENT ON COLUMN sys_department.leader_user_id IS '负责人用户 ID';
COMMENT ON COLUMN sys_department.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_department.status IS '部门状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_department.remark IS '备注';

CREATE TABLE sys_post (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_post_code
ON sys_post (code);

CREATE INDEX idx_sys_post_status
ON sys_post (status);

CREATE INDEX idx_sys_post_deleted_at
ON sys_post (deleted_at);

COMMENT ON TABLE sys_post IS '岗位表';
COMMENT ON COLUMN sys_post.code IS '岗位编码';
COMMENT ON COLUMN sys_post.name IS '岗位名称';
COMMENT ON COLUMN sys_post.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_post.status IS '岗位状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_post.remark IS '备注';

CREATE TABLE sys_user_post (
  id BIGSERIAL PRIMARY KEY,
  user_id BIGINT NOT NULL,
  post_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_sys_user_post_user_post
ON sys_user_post (user_id, post_id);

CREATE INDEX idx_sys_user_post_user_id
ON sys_user_post (user_id);

CREATE INDEX idx_sys_user_post_post_id
ON sys_user_post (post_id);

COMMENT ON TABLE sys_user_post IS '用户岗位关系表';
COMMENT ON COLUMN sys_user_post.user_id IS '用户 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_user_post.post_id IS '岗位 ID，对应 sys_post.id';

CREATE TABLE sys_role_data_scope (
  id BIGSERIAL PRIMARY KEY,
  role_id BIGINT NOT NULL,
  department_id BIGINT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL
);

CREATE UNIQUE INDEX uk_sys_role_data_scope_role_department
ON sys_role_data_scope (role_id, department_id);

CREATE INDEX idx_sys_role_data_scope_role_id
ON sys_role_data_scope (role_id);

CREATE INDEX idx_sys_role_data_scope_department_id
ON sys_role_data_scope (department_id);

COMMENT ON TABLE sys_role_data_scope IS '角色自定义部门数据范围关系表';
COMMENT ON COLUMN sys_role_data_scope.role_id IS '角色 ID，对应 sys_role.id';
COMMENT ON COLUMN sys_role_data_scope.department_id IS '部门 ID，对应 sys_department.id';

CREATE TABLE sys_dict_type (
  id BIGSERIAL PRIMARY KEY,
  code VARCHAR(64) NOT NULL,
  name VARCHAR(64) NOT NULL,
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_dict_type_code ON sys_dict_type (code);
CREATE INDEX idx_sys_dict_type_status ON sys_dict_type (status);
CREATE INDEX idx_sys_dict_type_deleted_at ON sys_dict_type (deleted_at);

COMMENT ON TABLE sys_dict_type IS '系统字典类型表';
COMMENT ON COLUMN sys_dict_type.id IS '字典类型主键，数据库自增生成';
COMMENT ON COLUMN sys_dict_type.code IS '字典编码，系统内唯一';
COMMENT ON COLUMN sys_dict_type.name IS '字典名称';
COMMENT ON COLUMN sys_dict_type.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_dict_type.status IS '字典状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_dict_type.remark IS '备注';
COMMENT ON COLUMN sys_dict_type.created_at IS '创建时间';
COMMENT ON COLUMN sys_dict_type.updated_at IS '更新时间';
COMMENT ON COLUMN sys_dict_type.deleted_at IS '逻辑删除时间，NULL 表示未删除';

CREATE TABLE sys_dict_item (
  id BIGSERIAL PRIMARY KEY,
  type_id BIGINT NOT NULL,
  item_key VARCHAR(64) NOT NULL,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(255) NOT NULL,
  tag_type VARCHAR(32) NOT NULL DEFAULT '',
  sort INTEGER NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_dict_item_type_key ON sys_dict_item (type_id, item_key);
CREATE INDEX idx_sys_dict_item_type_id ON sys_dict_item (type_id);
CREATE INDEX idx_sys_dict_item_status ON sys_dict_item (status);
CREATE INDEX idx_sys_dict_item_deleted_at ON sys_dict_item (deleted_at);

COMMENT ON TABLE sys_dict_item IS '系统字典项表';
COMMENT ON COLUMN sys_dict_item.id IS '字典项主键，数据库自增生成';
COMMENT ON COLUMN sys_dict_item.type_id IS '字典类型 ID，对应 sys_dict_type.id';
COMMENT ON COLUMN sys_dict_item.item_key IS '字典项编码，同一类型内唯一';
COMMENT ON COLUMN sys_dict_item.label IS '字典项名称';
COMMENT ON COLUMN sys_dict_item.value IS '字典项值';
COMMENT ON COLUMN sys_dict_item.tag_type IS '前端标签样式提示';
COMMENT ON COLUMN sys_dict_item.sort IS '排序值，数字越小越靠前';
COMMENT ON COLUMN sys_dict_item.status IS '字典项状态：1 启用，2 禁用';
COMMENT ON COLUMN sys_dict_item.remark IS '备注';
COMMENT ON COLUMN sys_dict_item.created_at IS '创建时间';
COMMENT ON COLUMN sys_dict_item.updated_at IS '更新时间';
COMMENT ON COLUMN sys_dict_item.deleted_at IS '逻辑删除时间，NULL 表示未删除';

CREATE TABLE sys_attachment (
  id BIGSERIAL PRIMARY KEY,
  file_id BIGINT NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  category VARCHAR(64) NOT NULL DEFAULT '',
  biz_type VARCHAR(64) NOT NULL DEFAULT '',
  uploader_id BIGINT NOT NULL DEFAULT 0,
  status SMALLINT NOT NULL DEFAULT 1,
  remark VARCHAR(255) NOT NULL DEFAULT '',
  created_at TIMESTAMPTZ NOT NULL,
  updated_at TIMESTAMPTZ NOT NULL,
  deleted_at TIMESTAMPTZ NULL
);

CREATE UNIQUE INDEX uk_sys_attachment_file_id ON sys_attachment (file_id);
CREATE INDEX idx_sys_attachment_category ON sys_attachment (category);
CREATE INDEX idx_sys_attachment_biz_type ON sys_attachment (biz_type);
CREATE INDEX idx_sys_attachment_uploader_id ON sys_attachment (uploader_id);
CREATE INDEX idx_sys_attachment_status ON sys_attachment (status);
CREATE INDEX idx_sys_attachment_deleted_at ON sys_attachment (deleted_at);

COMMENT ON TABLE sys_attachment IS '附件中心表';
COMMENT ON COLUMN sys_attachment.id IS '附件记录主键，数据库自增生成';
COMMENT ON COLUMN sys_attachment.file_id IS '底层文件记录 ID，对应 sys_file.id';
COMMENT ON COLUMN sys_attachment.display_name IS '附件展示名，默认使用原始文件名';
COMMENT ON COLUMN sys_attachment.category IS '附件分类，例如 invoice、contract、avatar';
COMMENT ON COLUMN sys_attachment.biz_type IS '业务类型，用于区分模块接入来源';
COMMENT ON COLUMN sys_attachment.uploader_id IS '上传用户 ID，对应 sys_user.id';
COMMENT ON COLUMN sys_attachment.status IS '附件状态：1 启用，2 停用';
COMMENT ON COLUMN sys_attachment.remark IS '备注';
COMMENT ON COLUMN sys_attachment.created_at IS '创建时间';
COMMENT ON COLUMN sys_attachment.updated_at IS '更新时间';
COMMENT ON COLUMN sys_attachment.deleted_at IS '逻辑删除时间，NULL 表示未删除';

CREATE TABLE sys_notification (
    id         BIGSERIAL PRIMARY KEY,
    user_id    BIGINT NOT NULL,
    type       SMALLINT NOT NULL DEFAULT 1,
    title      VARCHAR(128) NOT NULL DEFAULT '',
    content    TEXT NOT NULL DEFAULT '',
    extra      JSONB,
    is_read    BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT NOW(),
    read_at    TIMESTAMP
);

CREATE INDEX idx_notification_user_unread ON sys_notification(user_id, is_read, created_at DESC);

-- ============================================================================
-- Built-in seed data
-- ============================================================================

INSERT INTO sys_role (id, code, name, sort, data_scope, status, remark, created_at, updated_at)
VALUES
  (1, 'super_admin', '超级管理员', 0, 'all', 1, '系统内置角色', NOW(), NOW());

INSERT INTO sys_menu (id, parent_id, type, code, title, path, component, icon, sort, status, remark, created_at, updated_at)
VALUES
  (100, 0, 1, 'iam', '权限管理', '/iam', '', 'shield', 20, 1, '系统内置目录', NOW(), NOW()),
  (101, 0, 1, 'system', '系统设置', '/system', '', 'setting', 30, 1, '系统内置目录', NOW(), NOW()),
  (102, 0, 1, 'audit', '审计监控', '/audit', '', 'pulse', 40, 1, '系统内置目录', NOW(), NOW()),
  (211, 100, 2, 'system:department', '部门管理', '/iam/departments', 'iam/DepartmentView', 'git-branch', 10, 1, '系统内置菜单', NOW(), NOW()),
  (1110, 211, 3, 'system:department:list', '查看部门', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1111, 211, 3, 'system:department:create', '创建部门', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1112, 211, 3, 'system:department:update', '编辑部门', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1113, 211, 3, 'system:department:status', '修改部门状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (212, 100, 2, 'system:post', '岗位管理', '/iam/posts', 'iam/PostView', 'briefcase', 20, 1, '系统内置菜单', NOW(), NOW()),
  (1120, 212, 3, 'system:post:list', '查看岗位', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1121, 212, 3, 'system:post:create', '创建岗位', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1122, 212, 3, 'system:post:update', '编辑岗位', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1123, 212, 3, 'system:post:status', '修改岗位状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (201, 100, 2, 'system:user', '用户管理', '/iam/users', 'iam/UserView', 'people', 30, 1, '系统内置菜单', NOW(), NOW()),
  (1010, 201, 3, 'system:user:list', '查看用户', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1011, 201, 3, 'system:user:create', '创建用户', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1012, 201, 3, 'system:user:update', '编辑用户', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1013, 201, 3, 'system:user:status', '修改用户状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1014, 201, 3, 'system:user:assign-role', '分配用户角色', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (202, 100, 2, 'system:role', '角色管理', '/iam/roles', 'iam/RoleView', 'shield', 40, 1, '系统内置菜单', NOW(), NOW()),
  (1020, 202, 3, 'system:role:list', '查看角色', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1021, 202, 3, 'system:role:create', '创建角色', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1022, 202, 3, 'system:role:update', '编辑角色', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1023, 202, 3, 'system:role:status', '修改角色状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1024, 202, 3, 'system:role:permission', '分配接口权限', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (1025, 202, 3, 'system:role:menu', '分配菜单权限', '', '', '', 60, 1, '系统内置按钮', NOW(), NOW()),
  (203, 100, 2, 'system:menu', '菜单管理', '/iam/menus', 'iam/MenuView', 'layers', 50, 1, '系统内置菜单', NOW(), NOW()),
  (1030, 203, 3, 'system:menu:list', '查看菜单', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1031, 203, 3, 'system:menu:create', '创建菜单', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1032, 203, 3, 'system:menu:update', '编辑菜单', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1033, 203, 3, 'system:menu:status', '修改菜单状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1034, 203, 3, 'system:menu:delete', '删除菜单', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (204, 101, 2, 'system:config', '系统配置', '/system/configs', 'system/ConfigView', 'cog', 10, 1, '系统内置菜单', NOW(), NOW()),
  (1040, 204, 3, 'system:config:list', '查看配置', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1041, 204, 3, 'system:config:create', '创建配置', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1042, 204, 3, 'system:config:update', '编辑配置', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1043, 204, 3, 'system:config:status', '修改配置状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1044, 204, 3, 'system:config:value', '读取配置值', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (209, 101, 2, 'system:dict', '数据字典', '/system/dicts', 'system/DictView', 'albums', 20, 1, '系统内置菜单', NOW(), NOW()),
  (1090, 209, 3, 'system:dict:type:list', '查看字典类型', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1091, 209, 3, 'system:dict:type:create', '创建字典类型', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1092, 209, 3, 'system:dict:type:update', '编辑字典类型', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1093, 209, 3, 'system:dict:type:status', '修改字典类型状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (1094, 209, 3, 'system:dict:item:list', '查看字典项', '', '', '', 50, 1, '系统内置按钮', NOW(), NOW()),
  (1095, 209, 3, 'system:dict:item:create', '创建字典项', '', '', '', 60, 1, '系统内置按钮', NOW(), NOW()),
  (1096, 209, 3, 'system:dict:item:update', '编辑字典项', '', '', '', 70, 1, '系统内置按钮', NOW(), NOW()),
  (1097, 209, 3, 'system:dict:item:status', '修改字典项状态', '', '', '', 80, 1, '系统内置按钮', NOW(), NOW()),
  (205, 101, 2, 'system:file', '文件管理', '/system/files', 'system/FileView', 'folder', 30, 1, '系统内置菜单', NOW(), NOW()),
  (1050, 205, 3, 'system:file:list', '查看文件', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1051, 205, 3, 'system:file:upload', '上传文件', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (210, 101, 2, 'system:attachment', '附件中心', '/system/attachments', 'system/AttachmentView', 'files', 40, 1, '系统内置菜单', NOW(), NOW()),
  (1100, 210, 3, 'system:attachment:list', '查看附件', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1101, 210, 3, 'system:attachment:upload', '上传附件', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1102, 210, 3, 'system:attachment:update', '编辑附件', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1103, 210, 3, 'system:attachment:status', '修改附件状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (208, 101, 2, 'system:notice', '公告管理', '/system/notices', 'system/NoticeView', 'notifications', 50, 1, '系统内置菜单', NOW(), NOW()),
  (1080, 208, 3, 'system:notice:list', '查看公告', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (1081, 208, 3, 'system:notice:create', '创建公告', '', '', '', 20, 1, '系统内置按钮', NOW(), NOW()),
  (1082, 208, 3, 'system:notice:update', '编辑公告', '', '', '', 30, 1, '系统内置按钮', NOW(), NOW()),
  (1083, 208, 3, 'system:notice:status', '修改公告状态', '', '', '', 40, 1, '系统内置按钮', NOW(), NOW()),
  (200, 102, 2, 'system:health', '系统状态', '/audit/health', 'system/HealthView', 'pulse', 10, 1, '系统内置菜单', NOW(), NOW()),
  (1001, 200, 3, 'system:health:view', '查看系统状态', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (206, 102, 2, 'system:operation-log', '操作日志', '/audit/operation-logs', 'system/OperationLogView', 'list', 20, 1, '系统内置菜单', NOW(), NOW()),
  (1060, 206, 3, 'system:operation-log:list', '查看操作日志', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW()),
  (207, 102, 2, 'system:login-log', '登录日志', '/audit/login-logs', 'system/LoginLogView', 'time', 30, 1, '系统内置菜单', NOW(), NOW()),
  (1070, 207, 3, 'system:login-log:list', '查看登录日志', '', '', '', 10, 1, '系统内置按钮', NOW(), NOW());

INSERT INTO sys_dict_type (id, code, name, sort, status, remark, created_at, updated_at)
VALUES
  (1, 'common:yes-no', '是否字典', 10, 1, '系统内置基础字典', NOW(), NOW()),
  (2, 'notice:level', '公告级别', 20, 1, '系统内置公告字典', NOW(), NOW());

INSERT INTO sys_dict_item (id, type_id, item_key, label, value, tag_type, sort, status, remark, created_at, updated_at)
VALUES
  (1, 1, 'yes', '是', '1', 'success', 10, 1, '系统内置基础字典项', NOW(), NOW()),
  (2, 1, 'no', '否', '0', 'default', 20, 1, '系统内置基础字典项', NOW(), NOW()),
  (3, 2, 'info', '普通公告', 'info', 'info', 10, 1, '系统内置公告字典项', NOW(), NOW()),
  (4, 2, 'warning', '重要公告', 'warning', 'warning', 20, 1, '系统内置公告字典项', NOW(), NOW());

INSERT INTO casbin_rule (ptype, v0, v1, v2)
VALUES
  ('p', 'super_admin', '/api/v1/system/health', 'GET'),
  ('p', 'super_admin', '/api/v1/system/users', 'GET'),
  ('p', 'super_admin', '/api/v1/system/users', 'POST'),
  ('p', 'super_admin', '/api/v1/system/users/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/users/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/users/:id/roles', 'POST'),
  ('p', 'super_admin', '/api/v1/system/roles', 'GET'),
  ('p', 'super_admin', '/api/v1/system/roles', 'POST'),
  ('p', 'super_admin', '/api/v1/system/roles/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/roles/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/roles/:id/permissions', 'POST'),
  ('p', 'super_admin', '/api/v1/system/roles/:id/menus', 'POST'),
  ('p', 'super_admin', '/api/v1/system/menus', 'GET'),
  ('p', 'super_admin', '/api/v1/system/menus', 'POST'),
  ('p', 'super_admin', '/api/v1/system/menus/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/menus/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/menus/:id/delete', 'POST'),
  ('p', 'super_admin', '/api/v1/system/departments', 'GET'),
  ('p', 'super_admin', '/api/v1/system/departments', 'POST'),
  ('p', 'super_admin', '/api/v1/system/departments/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/departments/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/posts', 'GET'),
  ('p', 'super_admin', '/api/v1/system/posts', 'POST'),
  ('p', 'super_admin', '/api/v1/system/posts/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/posts/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/configs', 'GET'),
  ('p', 'super_admin', '/api/v1/system/configs', 'POST'),
  ('p', 'super_admin', '/api/v1/system/configs/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/configs/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/configs/value/:key', 'GET'),
  ('p', 'super_admin', '/api/v1/system/dict-types', 'GET'),
  ('p', 'super_admin', '/api/v1/system/dict-types', 'POST'),
  ('p', 'super_admin', '/api/v1/system/dict-types/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/dict-types/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/dict-items', 'GET'),
  ('p', 'super_admin', '/api/v1/system/dict-items', 'POST'),
  ('p', 'super_admin', '/api/v1/system/dict-items/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/dict-items/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/files', 'GET'),
  ('p', 'super_admin', '/api/v1/system/files', 'POST'),
  ('p', 'super_admin', '/api/v1/system/attachments', 'GET'),
  ('p', 'super_admin', '/api/v1/system/attachments', 'POST'),
  ('p', 'super_admin', '/api/v1/system/attachments/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/attachments/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/notices', 'GET'),
  ('p', 'super_admin', '/api/v1/system/notices', 'POST'),
  ('p', 'super_admin', '/api/v1/system/notices/:id/update', 'POST'),
  ('p', 'super_admin', '/api/v1/system/notices/:id/status', 'POST'),
  ('p', 'super_admin', '/api/v1/system/operation-logs', 'GET'),
  ('p', 'super_admin', '/api/v1/system/login-logs', 'GET'),
  ('p', 'super_admin', '/api/v1/system/notifications', 'GET'),
  ('p', 'super_admin', '/api/v1/system/notifications/unread-count', 'GET'),
  ('p', 'super_admin', '/api/v1/system/notifications/mark-read', 'POST'),
  ('p', 'super_admin', '/api/v1/system/notifications/mark-all-read', 'POST');

INSERT INTO sys_role_menu (role_id, menu_id, created_at, updated_at)
VALUES
  (1, 100, NOW(), NOW()),
  (1, 101, NOW(), NOW()),
  (1, 102, NOW(), NOW()),
  (1, 211, NOW(), NOW()),
  (1, 1110, NOW(), NOW()),
  (1, 1111, NOW(), NOW()),
  (1, 1112, NOW(), NOW()),
  (1, 1113, NOW(), NOW()),
  (1, 212, NOW(), NOW()),
  (1, 1120, NOW(), NOW()),
  (1, 1121, NOW(), NOW()),
  (1, 1122, NOW(), NOW()),
  (1, 1123, NOW(), NOW()),
  (1, 201, NOW(), NOW()),
  (1, 1010, NOW(), NOW()),
  (1, 1011, NOW(), NOW()),
  (1, 1012, NOW(), NOW()),
  (1, 1013, NOW(), NOW()),
  (1, 1014, NOW(), NOW()),
  (1, 202, NOW(), NOW()),
  (1, 1020, NOW(), NOW()),
  (1, 1021, NOW(), NOW()),
  (1, 1022, NOW(), NOW()),
  (1, 1023, NOW(), NOW()),
  (1, 1024, NOW(), NOW()),
  (1, 1025, NOW(), NOW()),
  (1, 203, NOW(), NOW()),
  (1, 1030, NOW(), NOW()),
  (1, 1031, NOW(), NOW()),
  (1, 1032, NOW(), NOW()),
  (1, 1033, NOW(), NOW()),
  (1, 1034, NOW(), NOW()),
  (1, 204, NOW(), NOW()),
  (1, 1040, NOW(), NOW()),
  (1, 1041, NOW(), NOW()),
  (1, 1042, NOW(), NOW()),
  (1, 1043, NOW(), NOW()),
  (1, 1044, NOW(), NOW()),
  (1, 209, NOW(), NOW()),
  (1, 1090, NOW(), NOW()),
  (1, 1091, NOW(), NOW()),
  (1, 1092, NOW(), NOW()),
  (1, 1093, NOW(), NOW()),
  (1, 1094, NOW(), NOW()),
  (1, 1095, NOW(), NOW()),
  (1, 1096, NOW(), NOW()),
  (1, 1097, NOW(), NOW()),
  (1, 205, NOW(), NOW()),
  (1, 1050, NOW(), NOW()),
  (1, 1051, NOW(), NOW()),
  (1, 210, NOW(), NOW()),
  (1, 1100, NOW(), NOW()),
  (1, 1101, NOW(), NOW()),
  (1, 1102, NOW(), NOW()),
  (1, 1103, NOW(), NOW()),
  (1, 208, NOW(), NOW()),
  (1, 1080, NOW(), NOW()),
  (1, 1081, NOW(), NOW()),
  (1, 1082, NOW(), NOW()),
  (1, 1083, NOW(), NOW()),
  (1, 200, NOW(), NOW()),
  (1, 1001, NOW(), NOW()),
  (1, 206, NOW(), NOW()),
  (1, 1060, NOW(), NOW()),
  (1, 207, NOW(), NOW()),
  (1, 1070, NOW(), NOW());

SELECT setval(pg_get_serial_sequence('sys_role', 'id'), COALESCE((SELECT MAX(id) FROM sys_role), 1), true);
SELECT setval(pg_get_serial_sequence('sys_menu', 'id'), COALESCE((SELECT MAX(id) FROM sys_menu), 1), true);
SELECT setval(pg_get_serial_sequence('sys_dict_type', 'id'), COALESCE((SELECT MAX(id) FROM sys_dict_type), 1), true);
SELECT setval(pg_get_serial_sequence('sys_dict_item', 'id'), COALESCE((SELECT MAX(id) FROM sys_dict_item), 1), true);

-- ============================================================================
-- Migration baseline
-- ============================================================================

CREATE TABLE IF NOT EXISTS schema_migrations (version BIGINT NOT NULL PRIMARY KEY, dirty BOOLEAN NOT NULL);
INSERT INTO schema_migrations (version, dirty) VALUES (1, false)
ON CONFLICT (version) DO UPDATE SET dirty = EXCLUDED.dirty;
