import type { GlobalThemeOverrides } from 'naive-ui'

export const themeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#14B8A6',
    primaryColorHover: '#0F9F93',
    primaryColorPressed: '#0D8B82',
    primaryColorSuppl: '#14B8A6',
    bodyColor: '#F6F8FB',
    cardColor: '#FFFFFF',
    modalColor: '#FFFFFF',
    popoverColor: '#FFFFFF',
    borderColor: '#E6ECF3',
    borderRadius: '12px',
    borderRadiusSmall: '10px',
    textColorBase: '#0F172A',
    textColor1: '#0F172A',
    textColor2: '#334155',
    textColor3: '#64748B',
    fontFamily:
      '"Inter", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  Card: {
    borderRadius: '18px',
    borderColor: '#E6ECF3',
    color: '#FFFFFF',
    paddingMedium: '24px',
    boxShadow: '0 8px 24px rgba(15, 23, 42, 0.06)',
  },
  Button: {
    borderRadiusMedium: '12px',
    borderRadiusSmall: '10px',
    heightMedium: '38px',
    heightSmall: '30px',
    fontSizeMedium: '14px',
    fontSizeSmall: '13px',
    colorPrimary: '#14B8A6',
    colorHoverPrimary: '#0F9F93',
    colorPressedPrimary: '#0D8B82',
    colorFocusPrimary: '#12A898',
    colorGhost: '#FFFFFF',
    colorGhostHover: '#F8FFFE',
    borderGhost: '1px solid #DDE6F0',
    borderGhostHover: '1px solid rgba(20, 184, 166, 0.35)',
    textColorGhost: '#334155',
    textColorGhostHover: '#0F766E',
  },
  Input: {
    borderRadius: '12px',
    heightMedium: '38px',
    heightSmall: '38px',
    borderColor: '#E6ECF3',
    borderHover: '#CBD5E1',
    borderFocus: '#14B8A6',
    boxShadowFocus: '0 0 0 3px rgba(20, 184, 166, 0.12)',
    placeholderColor: '#B0BEC5',
  },
  Select: {
    peers: {
      InternalSelection: {
        borderRadius: '12px',
        heightMedium: '38px',
        heightSmall: '38px',
        borderHover: '#CBD5E1',
        borderFocus: '#14B8A6',
        boxShadowFocus: '0 0 0 3px rgba(20, 184, 166, 0.12)',
        textColor: '#0F172A',
      },
    },
  },
  Tag: {
    borderRadius: '999px',
    heightMedium: '26px',
    heightSmall: '22px',
  },
  Dropdown: {
    borderRadius: '12px',
    boxShadow: '0 12px 32px rgba(15, 23, 42, 0.12)',
  },
  Menu: {
    itemHeight: '50px',
    borderRadius: '12px',
    itemTextColorInverted: 'rgba(255, 255, 255, 0.72)',
    itemTextColorHoverInverted: '#FFFFFF',
    itemTextColorActiveInverted: '#5EEAD4',
    itemTextColorActiveHoverInverted: '#5EEAD4',
    itemTextColorChildActiveInverted: '#5EEAD4',
    itemTextColorChildActiveHoverInverted: '#5EEAD4',
    itemIconColorInverted: 'rgba(255, 255, 255, 0.65)',
    itemIconColorHoverInverted: '#FFFFFF',
    itemIconColorActiveInverted: '#5EEAD4',
    itemIconColorActiveHoverInverted: '#5EEAD4',
    itemIconColorChildActiveInverted: '#5EEAD4',
    itemIconColorChildActiveHoverInverted: '#5EEAD4',
    itemColorActiveInverted: 'rgba(20, 184, 166, 0.14)',
    itemColorActiveHoverInverted: 'rgba(20, 184, 166, 0.18)',
    itemColorActiveCollapsedInverted: 'rgba(20, 184, 166, 0.18)',
    itemColorHoverInverted: 'rgba(255, 255, 255, 0.08)',
    arrowIconColorInverted: 'rgba(255, 255, 255, 0.5)',
    arrowColorChildActiveInverted: '#5EEAD4',
    arrowColorChildActiveHoverInverted: '#5EEAD4',
    peers: {
      Dropdown: {
        optionTextColorInverted: 'rgba(255, 255, 255, 0.72)',
        optionTextColorHoverInverted: '#FFFFFF',
        optionTextColorActiveInverted: '#5EEAD4',
        optionTextColorChildActiveInverted: '#5EEAD4',
        optionColorHoverInverted: 'rgba(255, 255, 255, 0.08)',
        optionColorActiveInverted: 'rgba(20, 184, 166, 0.18)',
      },
    },
  },
  Layout: {
    headerBorderColor: '#E6ECF3',
  },
  DataTable: {
    borderRadius: '0px',
    borderColor: '#E6ECF3',
    thColor: '#F8FAFC',
    thTextColor: '#334155',
    thFontWeight: '600',
    tdColor: '#FFFFFF',
    tdTextColor: '#0F172A',
    tdColorHover: '#F8FFFE',
    borderColorModal: '#E6ECF3',
  },
  Pagination: {
    itemBorderRadius: '8px',
    itemTextColor: '#64748B',
    itemTextColorHover: '#0F766E',
    itemTextColorActive: '#FFFFFF',
    itemTextColorPressed: '#FFFFFF',
    itemColorActive: '#14B8A6',
    itemColorHover: 'rgba(20, 184, 166, 0.08)',
    itemColorPressed: '#0D8B82',
    itemBorder: '1px solid transparent',
    itemBorderHover: '1px solid rgba(20, 184, 166, 0.24)',
    itemBorderActive: '1px solid transparent',
    itemSizeMedium: '32px',
  },
  Modal: {
    borderRadius: '16px',
  },
  Drawer: {
    borderRadius: '18px',
  },
  Popconfirm: {
    borderRadius: '12px',
  },
  Tabs: {
    tabTextColorActiveLine: '#0F766E',
    tabTextColorHoverLine: '#0F766E',
    barColor: '#14B8A6',
  },
  Alert: {
    borderRadius: '12px',
  },
  Empty: {
    textColor: '#94A3B8',
  },
}

export const darkThemeOverrides: GlobalThemeOverrides = {
  common: {
    primaryColor: '#14B8A6',
    primaryColorHover: '#2DD4BF',
    primaryColorPressed: '#0D8B82',
    primaryColorSuppl: '#14B8A6',
    bodyColor: '#0C1222',
    cardColor: '#151E31',
    modalColor: '#151E31',
    popoverColor: '#1A2536',
    borderColor: '#1E293B',
    borderRadius: '12px',
    borderRadiusSmall: '10px',
    textColorBase: '#E2E8F0',
    textColor1: '#E2E8F0',
    textColor2: '#CBD5E1',
    textColor3: '#94A3B8',
    fontFamily:
      '"Inter", ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif',
  },
  Card: {
    borderRadius: '18px',
    borderColor: '#1E293B',
    color: '#151E31',
    paddingMedium: '24px',
    boxShadow: '0 8px 24px rgba(0, 0, 0, 0.25)',
  },
  Button: {
    borderRadiusMedium: '12px',
    borderRadiusSmall: '10px',
    heightMedium: '38px',
    heightSmall: '30px',
    fontSizeMedium: '14px',
    fontSizeSmall: '13px',
    colorPrimary: '#14B8A6',
    colorHoverPrimary: '#2DD4BF',
    colorPressedPrimary: '#0D8B82',
    colorFocusPrimary: '#12A898',
    colorGhost: '#151E31',
    colorGhostHover: '#1A2536',
    borderGhost: '1px solid #1E293B',
    borderGhostHover: '1px solid rgba(20, 184, 166, 0.35)',
    textColorGhost: '#CBD5E1',
    textColorGhostHover: '#5EEAD4',
  },
  Input: {
    borderRadius: '12px',
    heightMedium: '38px',
    heightSmall: '38px',
    borderColor: '#1E293B',
    borderHover: '#334155',
    borderFocus: '#14B8A6',
    boxShadowFocus: '0 0 0 3px rgba(20, 184, 166, 0.12)',
    placeholderColor: '#4B5563',
    color: '#151E31',
    textColor: '#E2E8F0',
  },
  Select: {
    peers: {
      InternalSelection: {
        borderRadius: '12px',
        heightMedium: '38px',
        heightSmall: '38px',
        borderHover: '#334155',
        borderFocus: '#14B8A6',
        boxShadowFocus: '0 0 0 3px rgba(20, 184, 166, 0.12)',
        textColor: '#E2E8F0',
      },
    },
  },
  Tag: {
    borderRadius: '999px',
    heightMedium: '26px',
    heightSmall: '22px',
  },
  Dropdown: {
    borderRadius: '12px',
    boxShadow: '0 12px 32px rgba(0, 0, 0, 0.35)',
  },
  Menu: {
    itemHeight: '50px',
    borderRadius: '12px',
    itemTextColorInverted: 'rgba(255, 255, 255, 0.72)',
    itemTextColorHoverInverted: '#FFFFFF',
    itemTextColorActiveInverted: '#5EEAD4',
    itemTextColorActiveHoverInverted: '#5EEAD4',
    itemTextColorChildActiveInverted: '#5EEAD4',
    itemTextColorChildActiveHoverInverted: '#5EEAD4',
    itemIconColorInverted: 'rgba(255, 255, 255, 0.65)',
    itemIconColorHoverInverted: '#FFFFFF',
    itemIconColorActiveInverted: '#5EEAD4',
    itemIconColorActiveHoverInverted: '#5EEAD4',
    itemIconColorChildActiveInverted: '#5EEAD4',
    itemIconColorChildActiveHoverInverted: '#5EEAD4',
    itemColorActiveInverted: 'rgba(20, 184, 166, 0.14)',
    itemColorActiveHoverInverted: 'rgba(20, 184, 166, 0.18)',
    itemColorActiveCollapsedInverted: 'rgba(20, 184, 166, 0.18)',
    itemColorHoverInverted: 'rgba(255, 255, 255, 0.08)',
    arrowIconColorInverted: 'rgba(255, 255, 255, 0.5)',
    arrowColorChildActiveInverted: '#5EEAD4',
    arrowColorChildActiveHoverInverted: '#5EEAD4',
    peers: {
      Dropdown: {
        optionTextColorInverted: 'rgba(255, 255, 255, 0.72)',
        optionTextColorHoverInverted: '#FFFFFF',
        optionTextColorActiveInverted: '#5EEAD4',
        optionTextColorChildActiveInverted: '#5EEAD4',
        optionColorHoverInverted: 'rgba(255, 255, 255, 0.08)',
        optionColorActiveInverted: 'rgba(20, 184, 166, 0.18)',
      },
    },
  },
  Layout: {
    headerBorderColor: '#1E293B',
    color: '#0C1222',
  },
  DataTable: {
    borderRadius: '0px',
    borderColor: '#1E293B',
    thColor: '#111827',
    thTextColor: '#CBD5E1',
    thFontWeight: '600',
    tdColor: '#151E31',
    tdTextColor: '#E2E8F0',
    tdColorHover: '#1A2536',
    borderColorModal: '#1E293B',
  },
  Pagination: {
    itemBorderRadius: '8px',
    itemTextColor: '#94A3B8',
    itemTextColorHover: '#5EEAD4',
    itemTextColorActive: '#FFFFFF',
    itemTextColorPressed: '#FFFFFF',
    itemColorActive: '#14B8A6',
    itemColorHover: 'rgba(20, 184, 166, 0.12)',
    itemColorPressed: '#0D8B82',
    itemBorder: '1px solid transparent',
    itemBorderHover: '1px solid rgba(20, 184, 166, 0.24)',
    itemBorderActive: '1px solid transparent',
    itemSizeMedium: '32px',
  },
  Modal: {
    borderRadius: '16px',
  },
  Drawer: {
    borderRadius: '18px',
  },
  Popconfirm: {
    borderRadius: '12px',
  },
  Tabs: {
    tabTextColorActiveLine: '#5EEAD4',
    tabTextColorHoverLine: '#5EEAD4',
    barColor: '#14B8A6',
  },
  Alert: {
    borderRadius: '12px',
  },
  Empty: {
    textColor: '#64748B',
  },
}
