#!/usr/bin/env bash

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MIGRATIONS_DIR="${ROOT_DIR}/server/migrations"

build_full_sql() {
  local dialect="$1"
  local source_dir="${MIGRATIONS_DIR}/${dialect}"
  local output_file="${source_dir}/full_schema_and_seed.sql"
  local tmp_file

  tmp_file="$(mktemp)"
  trap 'rm -f "${tmp_file}"' RETURN

  {
    printf '%s\n' "-- Generated from server/migrations/${dialect}/*.up.sql"
    printf '%s\n' "-- Do not edit this file manually."
    printf '%s\n' "--"
    printf '%s\n' "-- Covers schema + built-in seed data."
    printf '%s\n' "-- Does NOT create the first admin user."
    printf '%s\n' "-- Create the first admin with POST /api/v1/setup/init after import."
    printf '\n'

    find "${source_dir}" -maxdepth 1 -type f -name '*.up.sql' ! -name 'full_schema_and_seed.sql' | sort | while read -r file; do
      printf '%s\n' "-- ============================================================================"
      printf '%s\n' "-- Source: ${dialect}/$(basename "${file}")"
      printf '%s\n' "-- ============================================================================"
      cat "${file}"
      printf '\n\n'
    done
  } > "${tmp_file}"

  mv "${tmp_file}" "${output_file}"
  trap - RETURN
}

build_full_sql "mysql"
build_full_sql "postgres"
